<?php

namespace Database\Seeders;

use App\Models\QaTestCase;
use Illuminate\Database\Seeder;

/**
 * QA Test Case Catalog Seeder.
 *
 * Catalog ini hasil enumerasi 5 agent paralel atas seluruh codebase
 * (controllers, services, jobs). Tiap entry: [feature, interaction, roles, title].
 * Roles: root, superadmin, admin, dpo, maker, viewer (atau 'any' / 'public').
 *
 * Total ~700+ test cases mencakup:
 *   - 6 universal CRUD modules (ropa, dpia, dsr, consent, breach, data-discovery)
 *   - Bespoke modules (gap, simulation, vendor_risk, cross_border, document_maker, contract/policy review, person_scan, rtp, maturity, retention, kb, containment, breach_reports, dsr_apps, posture, threat_intel)
 *   - AI ecosystem (ai_agent, ai_chat, ai_providers, ai_credits, ai_features, ai_jobs, document_maker, ocr, voice_tts, avatar, log_analyzer)
 *   - Root + system (license, tenant_provisioning, lifecycle, menu_registry, system_settings, system_update, audit_log, alerts, notifications, kb, tenant_roles, user_mgmt, org, auth, partner_api, public_cms)
 *   - User-facing (onboarding, dashboard, profile, white_label, idle_timeout, custom_wizard, dept/positions, comments, archive, kb, export, public_dsr, preference_center, embed, locale, search/filter, bulk, file_upload, settings, dsr_app, cookie)
 *
 * Built-in cases tidak boleh dihapus dari UI — set is_active=false aja.
 */
class QaTestCaseSeeder extends Seeder
{
    public function run(): void
    {
        $catalog = $this->catalog();
        $sortBase = 0;

        foreach ($catalog as $module => $items) {
            $sortBase += 100;
            foreach ($items as $i => $row) {
                QaTestCase::updateOrCreate(
                    [
                        'module' => $module,
                        'feature' => $row[0],
                        'interaction' => $row[1],
                    ],
                    [
                        'title' => $row[3],
                        'description' => $row[4] ?? null,
                        'applicable_roles' => $row[2],
                        'is_built_in' => true,
                        'is_active' => true,
                        'sort_order' => $sortBase + $i,
                    ]
                );
            }
        }
    }

    /**
     * Catalog data structure: module => [[feature, interaction, roles, title, description?], ...]
     *
     * @return array<string,array<int,array{0:string,1:string,2:array<int,string>,3:string,4?:string}>>
     */
    private function catalog(): array
    {
        return array_merge(
            $this->universalCrudModules(),
            $this->bespokeModules(),
            $this->aiEcosystem(),
            $this->rootSystem(),
            $this->userFacing(),
        );
    }

    private function universalCrudModules(): array
    {
        $standardCrud = function (array $writeRoles, array $readRoles, string $moduleLabel): array {
            return [
                ['crud', 'list_active', $readRoles, "List active {$moduleLabel}", 'GET list, soft-delete excluded, org-scoped'],
                ['crud', 'list_trashed', ['admin', 'dpo'], "List trashed {$moduleLabel}", 'GET ?trash=1'],
                ['crud', 'show', $readRoles, "Show single {$moduleLabel}", 'GET /{id}'],
                ['crud', 'create', $writeRoles, "Create {$moduleLabel}", 'POST with required fields, auto-gen code'],
                ['crud', 'update_basic', $writeRoles, 'Update basic fields', 'PUT/PATCH'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Soft delete (move to trash)'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore from trash'],
                ['crud', 'hard_delete', ['admin', 'dpo'], 'Hard delete (force from trash)'],
                ['crud', 'search_filter', $readRoles, 'Search by name/code/description'],
                ['crud', 'pagination', $readRoles, 'Cursor pagination'],
                ['custom_fields', 'add_field_value', $writeRoles, 'Add custom field value per record'],
                ['custom_fields', 'edit_field_value', $writeRoles, 'Edit custom field value'],
                ['custom_fields', 'delete_field_value', ['admin', 'dpo'], 'Delete custom field value'],
                ['custom_section', 'add_section', ['admin', 'dpo'], 'Add custom wizard section'],
                ['custom_section', 'edit_section', ['admin', 'dpo'], 'Edit custom section'],
                ['custom_section', 'delete_section', ['admin', 'dpo'], 'Delete custom section'],
                ['custom_section', 'reorder_sections', ['admin', 'dpo'], 'Reorder custom sections'],
                ['permission', 'deny_without_read', ['viewer'], 'Deny GET if missing :read permission'],
                ['permission', 'deny_without_write', ['viewer'], 'Deny POST/PUT if missing :write'],
                ['audit', 'history_endpoint', $writeRoles, 'GET /{id}/history (audit log)'],
                ['export', 'export_csv', $readRoles, 'Export CSV'],
            ];
        };

        $writeRoles = ['admin', 'dpo', 'maker'];
        $readRoles = ['admin', 'dpo', 'maker', 'viewer'];

        return [
            'ropa' => array_merge($standardCrud($writeRoles, $readRoles, 'RoPA'), [
                ['wizard', 'step_1_identitas', $writeRoles, 'Wizard step 1 — Identitas (processing_activity, division, pic)'],
                ['wizard', 'step_2_tujuan_dasar', $writeRoles, 'Wizard step 2 — Tujuan & Dasar Hukum'],
                ['wizard', 'step_3_kategori_data', $writeRoles, 'Wizard step 3 — Data Categories & Subjects'],
                ['wizard', 'step_4_penerima_data', $writeRoles, 'Wizard step 4 — Recipients & Sharing'],
                ['wizard', 'step_5_periode_retensi', $writeRoles, 'Wizard step 5 — Retention Period'],
                ['wizard', 'step_6_dpo_team', $writeRoles, 'Wizard step 6 — DPO Team'],
                ['wizard', 'step_7_keamanan_retensi', $writeRoles, 'Wizard step 7 — Security Measures'],
                ['wizard', 'sistem_terkait_link', $writeRoles, 'Link Information Systems via sistem_terkait array'],
                ['auto_risk', 'compute_risk_level', $writeRoles, 'Auto-compute risk_level from wizard triggers'],
                ['auto_risk', 'risk_locked_override', ['admin', 'dpo'], 'risk_level_locked preserves manual override'],
                ['auto_dpia', 'create_draft_dpia_on_high', ['admin', 'dpo'], 'Auto-create DPIA draft when risk=HIGH'],
                ['auto_lia', 'create_lia_on_legitimate_interest', ['admin', 'dpo'], 'Auto-create LIA when legal_basis=legitimate_interest'],
                ['assignment', 'assign_users', ['admin', 'dpo'], 'Assign assignees array'],
                ['assignment', 'lock_on_non_draft', ['admin', 'dpo'], 'Block reassign when status not draft/in_progress'],
                ['approval', 'submit_for_approval', $writeRoles, 'Status → waiting (submit DPO approval)'],
                ['approval', 'dpo_approve', ['admin', 'dpo'], 'DPO approves (status → approved)'],
                ['approval', 'dpo_reject', ['admin', 'dpo'], 'DPO rejects (status → in_progress)'],
                ['ai', 'ropa_analysis', $writeRoles, 'AI analyzer endpoint'],
                ['ai', 'autofill_from_text', $writeRoles, 'AI autofill wizard from text/document'],
                ['document_import', 'import_docx', $writeRoles, 'Upload DOCX → AI mapping'],
                ['document_import', 'import_pdf', $writeRoles, 'Upload PDF → OCR + AI mapping'],
                ['export', 'export_docx', $readRoles, 'Export DOCX template'],
                ['code_gen', 'legacy_format', $writeRoles, 'ROPA-YYYY-NNN'],
                ['code_gen', 'category_format', $writeRoles, 'ROPA-{CAT}-NNN with custom_number'],
            ]),
            'dpia' => array_merge($standardCrud($writeRoles, $readRoles, 'DPIA'), [
                ['wizard', 'step_1_informasi_dpia', $writeRoles, 'Step 1 — Informasi DPIA'],
                ['wizard', 'step_2_koneksi_ropa', $writeRoles, 'Step 2 — Koneksi RoPA (multi-link)'],
                ['wizard', 'step_3_potensi_risiko', $writeRoles, 'Step 3 — Potensi Risiko'],
                ['wizard', 'sync_ropa_pivot', $writeRoles, 'dpia_ropa pivot syncs with wizard data'],
                ['risk_assessment', 'likelihood_impact_scoring', $writeRoles, 'Likelihood × Impact → risk_level'],
                ['framework', 'list_categories', $readRoles, 'List org custom risk categories'],
                ['framework', 'create_category', ['admin', 'dpo'], 'Create custom category'],
                ['framework', 'edit_category', ['admin', 'dpo'], 'Edit/reorder category'],
                ['framework', 'delete_category', ['admin', 'dpo'], 'Delete category'],
                ['framework', 'add_risk_to_category', ['admin', 'dpo'], 'Add risk variant'],
                ['framework', 'reset_framework', ['admin', 'dpo'], 'Reset to default templates'],
                ['risk_event_templates', 'list_seeded_templates', $readRoles, 'GET seeded library (read-only)'],
                ['rtp', 'auto_generate', ['admin', 'dpo'], 'AI auto-generate RTP from risks'],
                ['rtp', 'list_items', $readRoles, 'GET mitigation items'],
                ['rtp', 'create_item', ['admin', 'dpo', 'maker'], 'Manual create RTP item'],
                ['rtp', 'update_item', ['admin', 'dpo', 'maker'], 'Update status/owner/deadline'],
                ['rtp', 'delete_item', ['admin', 'dpo'], 'Delete RTP item'],
                ['rtp', 'clean_orphans', ['admin', 'dpo'], 'Remove orphan items (deleted risk)'],
                ['rtp', 'cross_dpia_view', $readRoles, 'Aggregate view across all DPIAs'],
                ['ai', 'risk_scoring', $writeRoles, 'AI risk scoring endpoint'],
                ['ai', 'autofill_from_text', $writeRoles, 'AI autofill from description'],
                ['document_import', 'import_docx_pdf', $writeRoles, 'Upload DOCX/PDF → AI mapping'],
                ['export', 'export_risks_csv', $readRoles, 'Export risks CSV (one row per risk)'],
                ['export', 'export_docx', $readRoles, 'Export DPIA DOCX'],
            ]),
            'dsr' => array_merge($standardCrud($writeRoles, $readRoles, 'DSR'), [
                ['workflow', 'auto_deadline_72h', $writeRoles, 'deadline_at auto-set now+72h'],
                ['workflow', 'status_pending_to_in_progress', $writeRoles, 'pending_review → in_progress'],
                ['workflow', 'status_to_completed', $writeRoles, 'in_progress → completed'],
                ['workflow', 'status_rejected', $writeRoles, 'in_progress → rejected with reason'],
                ['scope_picker', 'list_scopes', $readRoles, 'GET scopes (Information Systems)'],
                ['scope_picker', 'add_scope', $writeRoles, 'Add Information System + request_types'],
                ['scope_picker', 'edit_scope', $writeRoles, 'Edit scope'],
                ['scope_picker', 'remove_scope', ['admin', 'dpo'], 'Remove scope'],
                ['scope_picker', 'auto_seed_from_app', $writeRoles, 'Auto-populate scopes from DSR app default'],
                ['scope_picker', 'auto_bump_status', $writeRoles, 'Status → in_progress when scopes added'],
                ['sql_pack', 'generate', $writeRoles, 'AI generates per-shard SQL pack'],
                ['sql_pack', 'download', $writeRoles, 'Download generated SQL pack'],
                ['verification', 'send_email', $writeRoles, 'Send verification email to subject'],
                ['verification', 'manual_verify', ['admin', 'dpo'], 'DPO marks verified manually'],
                ['verification', 'public_verify', ['public'], 'Subject verifies via public link'],
                ['execution', 'list_executions', $readRoles, 'List per-shard execution logs'],
                ['execution', 'update_status', $writeRoles, 'Mark shard completed/failed/pending'],
                ['execution', 'upload_evidence', $writeRoles, 'Attach proof file'],
                ['execution', 'download_evidence', $readRoles, 'Download evidence'],
                ['certificates', 'regenerate', $writeRoles, 'Regenerate subject + internal PDFs'],
                ['certificates', 'download_subject', $readRoles, 'Download subject certificate'],
                ['certificates', 'download_internal', $readRoles, 'Download internal certificate'],
                ['affected_ropas', 'list_via_scopes', $readRoles, 'List RoPAs linked via scopes'],
                ['ai', 'draft_response', $writeRoles, 'AI draft response letter'],
                ['ai', 'autofill', $writeRoles, 'AI autofill from request text'],
                ['public_api', 'config_endpoint', ['public'], 'GET /public/dsr/config/{embed_token}'],
                ['public_api', 'submit_endpoint', ['public'], 'POST submit from embedded widget'],
                ['code_gen', 'auto_request_id', $writeRoles, 'DSR-YYYY-NNN format'],
            ]),
            'consent' => array_merge($standardCrud($writeRoles, $readRoles, 'Consent'), [
                ['kind_preset', 'cookie_preset', $writeRoles, 'kind=cookie auto-applies banner preset'],
                ['kind_preset', 'contact_preset', $writeRoles, 'kind=contact auto-applies form preset'],
                ['kind_preset', 'analytics_preset', $writeRoles, 'kind=analytics preset'],
                ['items', 'list_items', $readRoles, 'List consent items (purposes)'],
                ['items', 'create_item', $writeRoles, 'Add purpose/category'],
                ['items', 'edit_item', $writeRoles, 'Edit item'],
                ['items', 'delete_item', ['admin', 'dpo'], 'Delete item'],
                ['records', 'list_records', $readRoles, 'List subject consent responses'],
                ['records', 'export_csv', $readRoles, 'Export consent records CSV'],
                ['ropa_link', 'sync_ropas', $writeRoles, 'Sync linked RoPAs many-to-many'],
                ['embed', 'get_snippet', $writeRoles, 'GET embed snippet (JS)'],
                ['embed', 'regenerate_token', $writeRoles, 'Regenerate embed_token'],
                ['embed', 'regenerate_api_keys', $writeRoles, 'Regenerate API keys pair'],
                ['embed', 'upload_logo', $writeRoles, 'Upload widget logo'],
                ['public_api', 'capture', ['public'], 'POST /public/consent/capture'],
                ['public_api', 'config', ['public'], 'GET /public/consent/config'],
                ['public_api', 'state', ['public'], 'GET /public/consent/state'],
                ['logs', 'list_logs', $readRoles, 'GET /consent-logs'],
                ['logs', 'cookie_logs_admin', $readRoles, 'GET /cookie-logs (Phase B)'],
                ['logs', 'cookie_stats', $readRoles, 'GET /cookie-logs/stats'],
                ['extract', 'preview', $writeRoles, 'Preview CRM extraction mapping'],
                ['extract', 'run_import', $writeRoles, 'Execute CRM import'],
                ['extract', 'history', $readRoles, 'List import runs'],
                ['crm', 'list_creds', $writeRoles, 'List CRM credentials'],
                ['crm', 'create_cred', $writeRoles, 'Add CRM API key'],
                ['crm', 'update_cred', $writeRoles, 'Update CRM config'],
                ['crm', 'delete_cred', ['admin', 'dpo'], 'Remove CRM connection'],
                ['crm', 'probe_cred', $writeRoles, 'Test CRM connection'],
                ['webhook', 'save_webhook', $writeRoles, 'Register webhook URL'],
                ['webhook', 'fire_on_change', ['system'], 'Async webhook on consent change'],
                ['ai', 'generate_consent', $writeRoles, 'AI draft consent text'],
                ['ai', 'audit_compliance', $writeRoles, 'AI audit compliance'],
                ['ai', 'autofill_items', $writeRoles, 'AI auto-generate items from domain'],
                ['code_gen', 'auto_collection_id', $writeRoles, 'CNT-YYYY-NNN format'],
            ]),
            'breach' => array_merge($standardCrud($writeRoles, $readRoles, 'Breach'), [
                ['create_extras', 'auto_apply_template', $writeRoles, 'Auto-apply case_type containment template'],
                ['create_extras', 'init_timeline_log', $writeRoles, 'Init timeline_log with detection entry'],
                ['create_extras', 'auto_notification_deadline', $writeRoles, 'notification_required → +72h deadline'],
                ['create_extras', 'multi_ropa_link', $writeRoles, 'linked_ropa_ids array'],
                ['workflow', 'status_detected_to_assessing', $writeRoles, 'Status transition'],
                ['workflow', 'status_assessing_to_containment', $writeRoles, 'Status transition'],
                ['workflow', 'status_to_notification', $writeRoles, 'Status → notification (urgent)'],
                ['workflow', 'status_to_closed', $writeRoles, 'Status → closed'],
                ['workflow', 'auto_timeline_on_status', $writeRoles, 'Auto-append timeline emoji per status'],
                ['containment', 'add_step', $writeRoles, 'Add containment step'],
                ['containment', 'update_step', $writeRoles, 'Update step status/owner'],
                ['containment', 'remove_step', $writeRoles, 'Remove step'],
                ['containment_template', 'list_templates', $readRoles, 'List case-type library'],
                ['containment_template', 'apply', $writeRoles, 'Apply template to breach'],
                ['containment_template', 'create', ['admin', 'dpo'], 'Create custom template'],
                ['containment_template', 'edit', ['admin', 'dpo'], 'Edit template'],
                ['containment_template', 'delete', ['admin', 'dpo'], 'Trash template'],
                ['raci', 'get_org_matrix', $readRoles, 'GET org RACI matrix'],
                ['raci', 'update_org_matrix', ['admin', 'dpo'], 'Update org-level RACI'],
                ['raci', 'override_per_breach', $writeRoles, 'Override RACI for this breach'],
                ['raci', 'apply_template', $writeRoles, 'Apply RACI template preset'],
                ['raci_template', 'crud_lifecycle', ['admin', 'dpo'], 'Full CRUD on RACI templates'],
                ['notification', 'auto_alert_on_create', ['admin', 'dpo'], 'Auto-alert DPO on critical breach'],
                ['notification', 'urgent_72h_deadline', ['admin', 'dpo'], 'Urgent flag in notification phase'],
                ['pdf_export', 'komdigi_report', $readRoles, 'Komdigi formal notification PDF'],
                ['pdf_export', 'subject_letter', $readRoles, 'Subject notification letter'],
                ['pdf_export', 'full_report', $readRoles, 'Full incident report PDF'],
                ['pdf_export', 'paper_size', $readRoles, 'Support a4|letter|legal|a3|a5|folio'],
                ['pdf_export', 'orientation', $readRoles, 'portrait|landscape'],
                ['ai', 'breach_advisor', $writeRoles, 'AI advisor recommendations'],
                ['ai', 'containment_steps', $writeRoles, 'AI suggest containment actions'],
                ['ai', 'autofill', $writeRoles, 'AI autofill from description'],
                ['integration', 'telegram_war_room', $writeRoles, 'Async push to Telegram'],
                ['integration', 'siem_sync', $writeRoles, 'Async sync to SIEM/SOAR'],
                ['code_gen', 'auto_incident_code', $writeRoles, 'BRC-YYYY-NNN format'],
            ]),
            'data_discovery' => array_merge($standardCrud($writeRoles, $readRoles, 'Information System'), [
                ['connection', 'test_connection', $writeRoles, 'Validate DB/API connectivity'],
                ['connection', 'encrypted_credentials', $writeRoles, 'Verify password/api_key wrapped at rest'],
                ['scan', 'standard_scan', $writeRoles, 'Schema introspection + column detection'],
                ['scan', 'ai_deep_scan', $writeRoles, 'AI deep scan with recommendations'],
                ['scan', 'get_scan_details', $readRoles, 'List discovered columns + classifications'],
                ['scan', 'list_changelogs', $readRoles, 'Schema change history'],
                ['scan', 'create_changelog', $writeRoles, 'Manual changelog entry'],
                ['scan', 'patrol_config', $writeRoles, 'AI daily patrol config'],
                ['column_classification', 'update_classification', $writeRoles, 'Update column PII category'],
                ['ropa_link', 'list_links', $readRoles, 'List RoPAs using this system'],
                ['ropa_link', 'sync_links', $writeRoles, 'Sync many-to-many'],
                ['ropa_link', 'detach_ropa', ['admin', 'dpo'], 'Remove single link'],
                ['search_ai', 'generate_sql', $writeRoles, 'Text-to-SQL from schema (2-step)'],
                ['search_ai', 'execute_sql', $writeRoles, 'Run AI-generated SQL'],
                ['search_ai', 'get_history', $readRoles, 'Past AI queries'],
                ['search_ai', 'clear_history', ['admin', 'dpo'], 'Bulk clear history'],
                ['decryptor', 'list_profiles', $readRoles, 'List keys (metadata only)'],
                ['decryptor', 'create_profile', $writeRoles, 'Register encryption key (wrapped)'],
                ['decryptor', 'rotate_key', $writeRoles, 'Rotate / update'],
                ['decryptor', 'delete_profile', ['admin', 'dpo'], 'Remove key'],
                ['decryptor', 'test_key', $writeRoles, 'Verify key against ciphertext'],
                ['leak', 'match_schema', $writeRoles, 'AI find candidate table from leak columns'],
                ['leak', 'verify_with_values', $writeRoles, 'Parametrized leak verify (no AI)'],
                ['leak', 'get_history', $readRoles, 'Recent verifications'],
                ['protection', 'get_assessment', $readRoles, 'Manual/AI security controls'],
                ['protection', 'save_assessment', $writeRoles, 'Update manual assessment'],
                ['protection', 'ai_assessment', $writeRoles, 'AI evaluate posture'],
                ['unstructured', 'scan_unstructured', $writeRoles, 'OCR + metadata extraction'],
                ['metadata_compare', 'compare', $writeRoles, 'Diff vs historical snapshots'],
                ['sample_query', 'generate_sample', $writeRoles, 'AI sample SELECT (limited rows)'],
                ['person_scan', 'list_plans', $readRoles, 'List Person Scan plans'],
                ['person_scan', 'create_plan', $writeRoles, 'Create cross-app person scan'],
                ['person_scan', 'execute_plan', $writeRoles, 'Run scan across systems'],
                ['person_scan', 'get_results', $readRoles, 'Person scan findings'],
                ['person_scan', 'reveal_results', ['admin', 'dpo'], 'Unlock PII display (data_discovery:reveal)'],
                ['person_scan', 'to_dsr', $writeRoles, 'Auto-create DSR from scan results'],
                ['ai', 'classification', $writeRoles, 'AI suggest PII categories'],
                ['permission', 'reveal_gate', ['viewer'], 'Deny reveal_results without permission'],
                ['export', 'export_columns_csv', $readRoles, 'Export columns + classifications CSV'],
            ]),
        ];
    }

    private function bespokeModules(): array
    {
        return [
            'gap_assessment' => [
                ['crud', 'list_assessments', ['admin', 'dpo', 'maker'], 'List assessments filterable by regulation + trash'],
                ['crud', 'show_assessment', ['admin', 'dpo', 'maker'], 'View assessment with full state'],
                ['crud', 'create_assessment', ['admin', 'dpo', 'maker'], 'Create for specific regulation (UUPDP, GDPR)'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore from trash'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['workflow', 'submit_answers', ['admin', 'dpo', 'maker'], 'Submit answers; triggers scoring'],
                ['workflow', 'upload_evidence', ['admin', 'dpo', 'maker'], 'Attach evidence to responses'],
                ['comparison', 'compare_historical', ['admin', 'dpo'], 'Side-by-side compare versions'],
                ['comparison', 'list_regulations', ['admin', 'dpo'], 'Active regulation frameworks'],
                ['custom', 'list_custom_questions', ['admin', 'dpo'], 'Org-specific questions'],
                ['custom', 'add_custom_question', ['admin', 'dpo'], 'Create with scoring logic'],
                ['custom', 'update_custom_question', ['admin', 'dpo'], 'Modify text/answers/weights'],
                ['custom', 'delete_custom_question', ['admin', 'dpo'], 'Remove'],
                ['ai', 'gap_remediation', ['admin', 'dpo'], 'AI remediation plan'],
                ['ai', 'gap_comparison', ['admin', 'dpo'], 'AI comparison + insights'],
                ['export', 'export_pdf', ['admin', 'dpo'], 'Export full + remediation PDF'],
            ],
            'simulation_drill' => [
                ['crud', 'list', ['admin', 'dpo', 'maker'], 'List simulations'],
                ['crud', 'show', ['admin', 'dpo', 'maker'], 'View drill with scenario'],
                ['crud', 'create', ['admin', 'dpo', 'maker'], 'Create from scenario template'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['workflow', 'start_drill', ['admin', 'dpo', 'maker'], 'Lock scenario; status in_progress'],
                ['workflow', 'submit_responses', ['admin', 'dpo', 'maker'], 'Participant responses'],
                ['workflow', 'list_templates', ['admin', 'dpo', 'maker'], 'Pre-built scenarios (ransomware, insider)'],
                ['ai', 'generate_scenario', ['admin', 'dpo'], 'AI custom scenario generation'],
                ['ai', 'analyze_responses', ['admin', 'dpo'], 'AI assessment of response quality'],
            ],
            'vendor_risk_tia' => [
                ['crud', 'list_vendors', ['admin', 'dpo'], 'List with latest assessment + DPA status'],
                ['crud', 'show_vendor', ['admin', 'dpo'], 'View detail + history'],
                ['crud', 'create_vendor', ['admin', 'dpo'], 'Add basic info'],
                ['crud', 'update_vendor', ['admin', 'dpo'], 'Edit + DPA expiry'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['assessment', 'deterministic', ['admin', 'dpo'], 'Pre-built questionnaire scoring'],
                ['assessment', 'list_categories', ['admin', 'dpo'], 'Risk categories picker'],
                ['assessment', 'get_questionnaire', ['admin', 'dpo'], 'Category questions + rules'],
                ['assessment', 'ai_assess', ['admin', 'dpo'], 'AI from vendor documents'],
                ['assessment', 'extract_document', ['admin', 'dpo'], 'Parse uploaded contracts/certs'],
                ['assessment', 'generate_questions', ['admin', 'dpo'], 'AI generate custom questions'],
                ['assessment', 'reassess', ['admin', 'dpo'], 'Re-run assessment'],
                ['document', 'upload', ['admin', 'dpo'], 'Attach DPA/SoC2'],
                ['document', 'delete', ['admin', 'dpo'], 'Remove document'],
                ['document', 'screen', ['admin', 'dpo'], 'AI scan vs org policy'],
                ['workflow', 'auto_tia_trigger', ['admin', 'dpo'], 'High-risk → seed draft TIA'],
            ],
            'cross_border' => [
                ['crud', 'list_transfers', ['admin', 'dpo'], 'List filterable by status'],
                ['crud', 'show_transfer', ['admin', 'dpo'], 'View with legal basis + risk'],
                ['crud', 'create_transfer', ['admin', 'dpo'], 'Auto-trigger TIA per Pasal 56'],
                ['crud', 'update_transfer', ['admin', 'dpo'], 'Modify legal basis/countries'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['country', 'list_countries', ['admin', 'dpo'], 'Adequacy + legal bases'],
                ['country', 'resolve_country', ['admin', 'dpo'], 'Lookup by code/name'],
                ['legal_basis', 'validate', ['admin', 'dpo'], 'Verify SCCs/BCRs valid'],
                ['workflow', 'status_flow', ['admin', 'dpo'], 'Draft → pending → approved/rejected → expired'],
                ['workflow', 'auto_tia', ['admin', 'dpo'], 'Auto-create draft TiaAssessment'],
            ],
            'document_maker' => [
                ['crud', 'list_documents', ['admin', 'dpo', 'maker'], 'List filterable by kind + trash'],
                ['crud', 'show_document', ['admin', 'dpo', 'maker'], 'View sections + placeholders'],
                ['crud', 'generate_policy', ['admin', 'dpo', 'maker'], 'AI generate Policy from wizard'],
                ['crud', 'generate_contract', ['admin', 'dpo', 'maker'], 'AI generate Contract from wizard'],
                ['crud', 'manual_edit', ['admin', 'dpo', 'maker'], 'Edit sections + metadata (no AI)'],
                ['crud', 'soft_delete', ['admin', 'dpo', 'maker'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo', 'maker'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo', 'maker'], 'Permanent delete'],
                ['export', 'download_docx', ['admin', 'dpo', 'maker'], 'Export DOCX with formatting'],
                ['export', 'download_pdf', ['admin', 'dpo', 'maker'], 'Export PDF'],
                ['ai', 'self_check_compliance', ['admin', 'dpo', 'maker'], 'Self-check after generate'],
                ['ai', 'fix_compliance', ['admin', 'dpo'], 'AI add missing UU PDP clauses'],
                ['ai', 'recheck_compliance', ['admin', 'dpo'], 'Re-run after manual edits'],
                ['wizard', 'from_policy_review', ['admin', 'dpo', 'maker'], 'Wizard from policy-review/add'],
                ['wizard', 'from_contract_review', ['admin', 'dpo', 'maker'], 'Wizard from contract-review/add'],
            ],
            'contract_review' => [
                ['crud', 'list_reviews', ['admin', 'dpo'], 'List filterable by status + trash'],
                ['crud', 'show_review', ['admin', 'dpo'], 'View with AI analysis'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['ai', 'upload_pdf_docx', ['admin', 'dpo'], 'Upload for AI analysis'],
                ['ai', 'review_text', ['admin', 'dpo'], 'Review pasted text'],
                ['ai', 'history', ['admin', 'dpo'], 'Past AI analysis'],
                ['ai', 'dedup_window', ['admin', 'dpo'], 'Verify dedup 2-min window prevents double row'],
                ['ai', 'per_type_relevance', ['admin', 'dpo'], 'NDA/DPA/Vendor/Employment/Customer relevance map'],
                ['integration', 'launch_doc_maker', ['admin', 'dpo'], 'Create draft from review findings'],
            ],
            'policy_review' => [
                ['crud', 'list_reviews', ['admin', 'dpo'], 'List filterable'],
                ['crud', 'show_review', ['admin', 'dpo'], 'View with compliance gaps'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['ai', 'upload_doc', ['admin', 'dpo'], 'Upload PDF/DOCX'],
                ['ai', 'review_text', ['admin', 'dpo'], 'Review pasted text'],
                ['ai', 'per_type_scope_hint', ['admin', 'dpo'], 'Privacy Policy / SOP / Peraturan scope hints'],
                ['ai', 'dedup_window', ['admin', 'dpo'], 'Verify dedup 2-min window'],
                ['integration', 'launch_doc_maker', ['admin', 'dpo'], 'Create draft from review'],
            ],
            'risk_treatment_plan' => [
                ['aggregate', 'list_all_items', ['admin', 'dpo'], 'Cross-DPIA mitigation items'],
                ['aggregate', 'filter', ['admin', 'dpo'], 'By status/priority/owner/due/DPIA/search'],
                ['aggregate', 'dashboard', ['admin', 'dpo'], 'RTP summary (open, overdue, by owner)'],
                ['aggregate', 'facets', ['admin', 'dpo'], 'Filter facets'],
                ['per_dpia', 'list_for_dpia', ['admin', 'dpo'], 'GET /dpia/{id}/rtp'],
                ['per_dpia', 'create_item', ['admin', 'dpo', 'maker'], 'Create tied to risk'],
                ['per_dpia', 'auto_generate', ['admin', 'dpo'], 'AI auto-generate from risks'],
                ['per_dpia', 'clean_orphans', ['admin', 'dpo'], 'Remove orphan items'],
                ['per_dpia', 'update_item', ['admin', 'dpo', 'maker'], 'Update status/owner/deadline/evidence'],
                ['per_dpia', 'delete_item', ['admin', 'dpo'], 'Remove item'],
            ],
            'maturity_assessment' => [
                ['crud', 'list', ['admin', 'dpo'], 'Filterable by status/method/level'],
                ['crud', 'show', ['admin', 'dpo'], 'View with responses + scores'],
                ['crud', 'create', ['admin', 'dpo'], 'Create new assessment'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['method', 'questionnaire', ['admin', 'dpo'], '1-10 slider per question (18 questions)'],
                ['method', 'document_upload', ['admin', 'dpo'], 'Upload SOP; AI scores from content'],
                ['method', 'auto_derive', ['admin', 'dpo'], 'Auto-score from existing data'],
                ['response', 'upsert', ['admin', 'dpo'], 'Save single response + recompute'],
                ['response', 'bulk_upsert', ['admin', 'dpo'], 'Save multiple responses'],
                ['workflow', 'submit', ['admin', 'dpo'], 'Lock; draft → submitted'],
                ['workflow', 'publish', ['admin', 'dpo'], 'Finalize submitted → published'],
                ['ai', 'auto_derive', ['admin', 'dpo'], 'AI extract indicators from config'],
                ['ai', 'ask_ai', ['admin', 'dpo'], 'Chat-style Q&A during assessment'],
                ['ai', 'recommendations', ['admin', 'dpo'], 'AI improvement recommendations'],
                ['export', 'export_pdf', ['admin', 'dpo'], 'Branded PDF with score breakdown'],
                ['analytics', 'trend_view', ['admin', 'dpo'], 'Historical trend over time'],
            ],
            'retention_policy' => [
                ['crud', 'list', ['admin', 'dpo'], 'Filterable by trash + search'],
                ['crud', 'show', ['admin', 'dpo'], 'View trigger + rules'],
                ['crud', 'create', ['admin', 'dpo'], 'Master policy create'],
                ['crud', 'update', ['admin', 'dpo'], 'Modify; block if RoPA references'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Move to trash; in-use check'],
                ['crud', 'restore', ['admin', 'dpo'], 'Restore'],
                ['crud', 'force_delete', ['admin', 'dpo'], 'Permanent delete'],
                ['reference', 'in_use_check', ['admin', 'dpo'], 'Validate not referenced before delete'],
            ],
            'knowledge_base' => [
                ['crud', 'list_sections', ['admin', 'dpo', 'maker', 'viewer'], 'List shared + tenant sections'],
                ['crud', 'show_section', ['admin', 'dpo', 'maker', 'viewer'], 'View full content'],
                ['crud', 'create_shared', ['root', 'superadmin'], 'Create shared (org_id=null)'],
                ['crud', 'create_tenant', ['admin'], 'Create org-scoped section'],
                ['crud', 'update_shared', ['root', 'superadmin'], 'Edit shared'],
                ['crud', 'update_tenant', ['admin'], 'Edit tenant section (own org)'],
                ['crud', 'delete_shared', ['root', 'superadmin'], 'Delete shared'],
                ['crud', 'delete_tenant', ['admin'], 'Delete tenant section'],
                ['ai', 'rag_context_injection', ['admin', 'dpo', 'maker', 'viewer'], 'KB sections injected as RAG context'],
                ['visibility', 'shared_org_id_null', ['root', 'superadmin'], 'Verify shared = org_id=NULL'],
                ['search', 'free_text_search', ['admin', 'dpo', 'maker', 'viewer'], 'Search title/content/keywords'],
            ],
            'breach_reports' => [
                ['export', 'komdigi_pdf', ['admin', 'dpo'], 'Surat Notifikasi KOMDIGI 3x24h'],
                ['export', 'subject_letter_pdf', ['admin', 'dpo'], 'Subject notification letter'],
                ['export', 'full_report_pdf', ['admin', 'dpo'], 'Full incident report'],
                ['config', 'paper_size_param', ['admin', 'dpo'], '?size=a4|letter|legal|a3|a5|folio'],
                ['config', 'orientation_param', ['admin', 'dpo'], '?orientation=portrait|landscape'],
                ['branding', 'tenant_branding', ['admin', 'dpo'], 'Org logo/name from settings'],
            ],
            'dsr_apps' => [
                ['crud', 'list_apps', ['admin', 'dpo'], 'List registered external apps'],
                ['crud', 'show_app', ['admin', 'dpo'], 'View detail + tokens + metadata'],
                ['crud', 'create_app', ['admin', 'dpo'], 'Register new (app_code, name, redirect_url, logo)'],
                ['crud', 'update_app', ['admin', 'dpo'], 'Modify config'],
                ['crud', 'soft_delete', ['admin', 'dpo'], 'Deactivate'],
                ['crud', 'restore', ['admin', 'dpo'], 'Re-enable'],
                ['auth', 'regenerate_embed_token', ['admin', 'dpo'], 'Rotate widget token'],
                ['auth', 'regenerate_api_keys', ['admin', 'dpo'], 'Rotate API key pair'],
                ['logo', 'upload_logo', ['admin', 'dpo'], 'Upload widget logo'],
                ['logo', 'public_get_logo', ['public'], 'Fetch logo for widget'],
                ['embed', 'get_snippet', ['admin', 'dpo'], 'HTML/JS embed snippet'],
                ['captcha', 'configure_captcha', ['admin', 'dpo'], 'Turnstile/hCaptcha/reCAPTCHA'],
                ['nda', 'enable_nda_flow', ['admin', 'dpo'], 'Toggle requires_nda_for_access'],
                ['nda', 'select_template', ['admin', 'dpo'], 'Pick NDA document template'],
                ['nda', 'choose_signing', ['admin', 'dpo'], 'e-signature/typed/upload-signed'],
                ['sla', 'set_response_sla', ['admin', 'dpo'], 'Response SLA days'],
                ['webhook', 'set_webhook', ['admin', 'dpo'], 'Webhook URL on completion'],
                ['webhook', 'test_webhook', ['admin', 'dpo'], 'Send test payload'],
                ['locale', 'set_app_locale', ['admin', 'dpo'], 'Public form language'],
                ['helper', 'assignable_users', ['admin', 'dpo'], 'Org user list for assignment picker'],
            ],
            'posture_findings' => [
                ['posture', 'live_score', ['admin'], 'Live posture (DSPM gauge)'],
                ['posture', 'trend_history', ['admin'], 'Historical trend (?days=30)'],
                ['posture', 'take_snapshot', ['admin'], 'Manual snapshot trigger'],
                ['findings', 'list', ['admin'], 'Filter status/severity/pillar/assignee'],
                ['findings', 'show', ['admin'], 'View detail with assignee'],
                ['findings', 'rematerialize', ['admin'], 'Force detector re-run'],
                ['findings', 'assign', ['admin'], 'Assign to user; notify'],
                ['findings', 'change_status', ['admin'], 'open → in_progress → resolved/accepted/dismissed'],
                ['findings', 'stats', ['admin'], 'By severity/status/pillar/overdue%'],
                ['findings', 'sla_due_at', ['admin'], 'Per severity/pillar SLA tracking'],
            ],
            'alerts' => [
                ['alert', 'list', ['admin', 'dpo', 'maker', 'viewer'], 'Scoped visibility (org/role/recipient)'],
                ['alert', 'count_badge', ['admin', 'dpo', 'maker', 'viewer'], 'Bell badge unread count'],
                ['alert', 'export_csv', ['admin', 'dpo'], 'Export with metadata'],
                ['alert', 'scan_now', ['admin', 'dpo'], 'Trigger AlertEngineService::runAllRules'],
                ['alert', 'mark_read', ['admin', 'dpo', 'maker', 'viewer'], 'Mark single read'],
                ['alert', 'mark_all_read', ['admin', 'dpo', 'maker', 'viewer'], 'Bulk mark read'],
                ['alert', 'acknowledge', ['admin', 'dpo'], 'Status → acknowledged'],
                ['alert', 'resolve', ['admin', 'dpo'], 'Status → resolved'],
                ['alert', 'dismiss', ['admin', 'dpo'], 'Status → dismissed'],
            ],
            'threat_intel' => [
                ['webhook', 'receive_alert', ['public'], 'POST /webhooks/threat-intel/{org_id}'],
                ['webhook', 'auth_via_secret', ['public'], 'X-Webhook-Secret header verification'],
                ['workflow', 'auto_create_breach', ['public'], 'Inbound alert → new breach incident'],
                ['provider', 'multi_provider', ['admin'], 'SOCRadar, Have I Been Pwned, custom'],
            ],
        ];
    }

    private function aiEcosystem(): array
    {
        return [
            'ai_agent' => [
                ['chat', 'send_message', ['admin', 'dpo', 'maker', 'viewer'], 'Send + streamed reply'],
                ['chat', 'file_upload', ['admin', 'dpo', 'maker'], 'PDF/DOCX/image; auto-switch document provider'],
                ['chat', 'conversation_history', ['admin', 'dpo', 'maker', 'viewer'], 'Last 10 messages'],
                ['tool', 'execute_read_only', ['admin', 'dpo', 'maker', 'viewer'], 'AI calls read tools without approval'],
                ['tool', 'propose_mutation', ['admin', 'dpo', 'maker'], 'AI proposes mutation; approval_required event'],
                ['tool', 'user_approve_action', ['admin', 'dpo', 'maker'], 'Explicit approval triggers tool with approved=true'],
                ['tool', 'user_reject_action', ['admin', 'dpo', 'maker'], 'Reject; no data modified'],
                ['tool', 'max_iterations_5', ['admin', 'dpo', 'maker', 'viewer'], 'AI hits 5 iterations; warn'],
                ['mention', 'autocomplete_modules', ['admin', 'dpo', 'maker', 'viewer'], '@ropa @dpia @gap @breach @dsr autocomplete'],
                ['credit', 'deduct_on_success', ['system'], '0.25 credit only after success'],
                ['credit', 'exhausted_402', ['admin', 'dpo', 'maker', 'viewer'], '402 if credits insufficient'],
                ['kb', 'context_injection', ['admin', 'dpo', 'maker', 'viewer'], 'KB sections in system prompt'],
                ['error', 'provider_unavailable', ['admin', 'dpo', 'maker', 'viewer'], '503 if no API key'],
                ['error', 'vision_model_check', ['admin', 'dpo', 'maker', 'viewer'], 'Reject image if no vision support'],
                ['error', 'heartbeat_streaming', ['admin', 'dpo', 'maker', 'viewer'], 'Heartbeat every 3s during long calls'],
                ['superadmin', 'list_users_tool', ['root', 'superadmin'], 'Query users (read-only)'],
                ['superadmin', 'list_licenses_tool', ['root', 'superadmin'], 'Read licenses'],
                ['superadmin', 'list_chat_history_tool', ['root', 'superadmin'], 'Search all conversations'],
            ],
            'ai_chat' => [
                ['chat', 'send_message', ['admin', 'dpo', 'maker', 'viewer'], 'KB-grounded streamed reply'],
                ['chat', 'kb_grounding_rag', ['admin', 'dpo', 'maker', 'viewer'], 'Top relevant KB sections injected'],
                ['chat', 'create_conversation', ['admin', 'dpo', 'maker', 'viewer'], 'Auto-create on first message'],
                ['chat', 'admin_takeover', ['root', 'superadmin'], 'Admin sends → status=admin_active'],
                ['chat', 'polling_messages', ['admin', 'dpo', 'maker', 'viewer'], 'Poll new messages after timestamp'],
                ['credit', 'deduct_0_25', ['system'], '0.25 credit per chat message'],
                ['credit', 'no_deduct_admin_takeover', ['system'], 'No deduct when admin replies'],
                ['error', 'no_provider_503', ['admin', 'dpo', 'maker', 'viewer'], '503 if no chat provider'],
                ['error', 'api_failure_502', ['admin', 'dpo', 'maker', 'viewer'], '502; truncate error 500 chars'],
                ['history', 'list_conversations_root', ['root', 'superadmin'], 'All conversations + search'],
                ['history', 'list_own_conversations', ['admin', 'dpo', 'maker', 'viewer'], 'Own conversations only'],
                ['history', 'get_messages', ['admin', 'dpo', 'maker', 'viewer'], 'Owner or superadmin auth'],
                ['kb', 'edit_kb', ['root', 'superadmin'], 'PUT update KB content'],
            ],
            'ai_providers' => [
                ['provider', 'list_active_public', ['admin', 'dpo', 'maker', 'viewer'], 'Active providers ordered'],
                ['provider', 'admin_list_all', ['root', 'superadmin'], 'Include inactive + trashed'],
                ['provider', 'create', ['root', 'superadmin'], 'New provider with auth_header'],
                ['provider', 'update', ['root', 'superadmin'], 'Modify + sort_order'],
                ['provider', 'delete', ['root', 'superadmin'], 'Soft-delete + cascade models'],
                ['provider', 'restore', ['root', 'superadmin'], 'Restore + models'],
                ['provider', 'force_delete', ['root', 'superadmin'], 'Permanent delete'],
                ['model', 'list', ['root', 'superadmin'], 'List per provider'],
                ['model', 'create', ['root', 'superadmin'], 'Add with supports_tools/vision/pricing'],
                ['model', 'update', ['root', 'superadmin'], 'Modify + sort_order'],
                ['model', 'delete', ['root', 'superadmin'], 'Soft-delete'],
                ['api_key', 'save_encrypted', ['admin'], 'AES-256 encrypted per-tenant'],
                ['api_key', 'test_connection', ['admin'], 'POST chat completion to verify'],
                ['api_key', 'remove', ['admin'], 'Delete + clear active selections'],
                ['active_selection', 'set_chat', ['admin'], 'Set active for chat mode'],
                ['active_selection', 'set_agent', ['admin'], 'Set active for agent mode'],
                ['active_selection', 'set_document', ['admin'], 'Set active for document mode'],
                ['active_selection', 'set_avatar', ['admin'], 'Set active for avatar mode'],
                ['active_selection', 'set_voice', ['admin'], 'Set active for voice mode'],
                ['active_selection', 'unset', ['admin'], 'Clear selection (no fallback)'],
                ['fallback_chain', 'agent_to_chat', ['system'], 'agent → chat fallback'],
                ['fallback_chain', 'document_to_chat', ['system'], 'document → chat fallback'],
                ['fallback_chain', 'org_to_global', ['system'], 'Tenant → global (org_id=NULL)'],
            ],
            'ai_credits' => [
                ['balance', 'monthly_lazy_reset', ['system'], 'Reset remaining if reset_at past'],
                ['balance', 'two_buckets', ['system'], 'remaining (monthly) + purchased (top-up)'],
                ['cost', 'autofill_1', ['admin', 'dpo', 'maker'], 'autofill RoPA/DPIA/Breach = 1.0'],
                ['cost', 'autofill_dsr_0_5', ['admin', 'dpo', 'maker'], 'DSR autofill = 0.5'],
                ['cost', 'analysis_1', ['admin', 'dpo', 'maker'], 'ropa_analysis/dpia_risk_scoring = 1.0'],
                ['cost', 'breach_advisor_1', ['admin', 'dpo', 'maker'], 'breach_advisor = 1.0'],
                ['cost', 'dsr_draft_0_5', ['admin', 'dpo', 'maker'], 'dsr_draft = 0.5'],
                ['cost', 'consent_generator_0_5', ['admin', 'dpo', 'maker'], 'consent_generator = 0.5'],
                ['cost', 'gap_remediation_1', ['admin', 'dpo', 'maker'], 'gap_remediation = 1.0'],
                ['cost', 'drill_2', ['admin', 'dpo', 'maker'], 'drill_scenario = 2.0'],
                ['cost', 'chat_0_25', ['admin', 'dpo', 'maker', 'viewer'], 'AI chat = 0.25'],
                ['cost', 'dashboard_summary_1', ['admin', 'dpo', 'maker'], 'dashboard_summary = 1.0'],
                ['deduction', 'on_success_only', ['system'], 'Deduct AFTER success; no deduct on failure'],
                ['deduction', 'priority_remaining_first', ['system'], 'Remaining → purchased overflow'],
                ['deduction', 'refund_failed', ['root', 'admin'], 'Refund via log ID'],
                ['logging', 'create_credit_log', ['system'], 'AiCreditLog with action_type/cost/status'],
                ['reporting', 'usage_breakdown', ['root', 'superadmin', 'admin'], 'By action_type + count'],
                ['reporting', 'recent_logs', ['root', 'superadmin', 'admin'], 'Last 50 with user attribution'],
                ['reporting', 'cross_tenant', ['root', 'superadmin'], 'All tenants summary'],
                ['error', 'exhausted_402', ['admin', 'dpo', 'maker', 'viewer'], '402 with cost hint'],
            ],
            'ai_features' => [
                ['gap_remediation', 'generate', ['admin', 'dpo', 'maker'], 'AI remediation roadmap'],
                ['ropa_analysis', 'analyze', ['admin', 'dpo', 'maker'], 'AI review of RoPA'],
                ['ropa_analysis', 'bulk_batch', ['admin'], 'Queue batch (BatchAiReviewJob)'],
                ['ropa_analysis', 'batch_status', ['admin', 'dpo', 'maker', 'viewer'], 'Poll batch progress'],
                ['dpia_risk_scoring', 'analyze', ['admin', 'dpo', 'maker'], 'AI risk matrix'],
                ['dpia_risk_scoring', 'bulk_batch', ['admin'], 'Queue batch DPIA reviews'],
                ['breach_advisor', 'advisor', ['admin', 'dpo', 'maker'], 'AI investigation + containment'],
                ['breach_advisor', 'containment_steps', ['admin', 'dpo', 'maker'], 'AI 10-item checklist'],
                ['dsr_draft', 'generate_response', ['admin', 'dpo', 'maker'], 'AI draft per request type'],
                ['consent_generator', 'generate', ['admin', 'dpo', 'maker'], 'AI consent form/policy snippet'],
                ['drill_scenario', 'generate', ['admin', 'dpo', 'maker'], 'AI drill (2.0 credits)'],
                ['drill_scenario', 'analysis', ['admin', 'dpo', 'maker', 'viewer'], 'AI post-drill analysis'],
                ['dashboard_summary', 'generate', ['admin', 'dpo', 'maker', 'viewer'], 'AI compliance summary'],
                ['autofill', 'wizard_ropa', ['admin', 'dpo', 'maker'], 'RoPA autofill from text'],
                ['autofill', 'wizard_dpia', ['admin', 'dpo', 'maker'], 'DPIA autofill'],
                ['autofill', 'wizard_breach', ['admin', 'dpo', 'maker'], 'Breach autofill'],
                ['autofill', 'wizard_dsr', ['admin', 'dpo', 'maker'], 'DSR autofill'],
                ['autofill', 'wizard_consent', ['admin', 'dpo', 'maker'], 'Consent items autofill'],
                ['raci', 'generate', ['admin', 'dpo'], 'AI generate RACI matrix'],
                ['feature_history', 'view_per_record', ['admin', 'dpo', 'maker', 'viewer'], 'Per-record AI history'],
                ['error', 'license_basic_403', ['admin', 'dpo', 'maker', 'viewer'], '403 if package_type=basic'],
                ['error', 'no_provider_503', ['admin', 'dpo', 'maker', 'viewer'], '503 if no provider'],
            ],
            'ai_jobs' => [
                ['dispatch', 'create_job_202', ['admin', 'dpo', 'maker'], 'API returns 202 + job_id immediately'],
                ['dispatch', 'queue_dispatch', ['system'], 'ProcessAiJob pushed to queue'],
                ['type', 'autofill', ['admin', 'dpo', 'maker'], 'Extract structured data via AiFieldMappingService'],
                ['type', 'analyzer', ['admin', 'dpo', 'maker'], 'Run AiAgentToolExecutor with job org_id'],
                ['type', 'summary', ['admin', 'dpo', 'maker'], 'Generate text summary'],
                ['type', 'person_scan_execute', ['admin', 'dpo', 'maker'], 'Discovery scan orchestrator'],
                ['progress', 'poll_status', ['admin', 'dpo', 'maker', 'viewer'], 'GET /api/ai/jobs/{id}'],
                ['progress', 'list_active', ['admin', 'dpo', 'maker', 'viewer'], 'GET active jobs'],
                ['retry', 'auto_retry_3', ['system'], 'Retry up to 3 with exponential backoff'],
                ['timeout', 'per_attempt_300s', ['system'], 'Per-attempt 300s timeout'],
                ['kill_switch', 'jobs_disabled', ['root', 'superadmin'], 'config(ai.jobs_enabled)=false → cancel'],
                ['error', 'log_to_db', ['system'], 'Errors persisted on job.error column'],
                ['credit', 'debit_on_done_only', ['system'], 'Deduct only on status=DONE'],
                ['audit', 'write_audit_log', ['system'], 'AuditLog ai_job.complete on success'],
            ],
            'ocr' => [
                ['primary', 'tesseract_image', ['admin', 'dpo', 'maker'], 'JPG/PNG/TIFF via tesseract CLI'],
                ['primary', 'pdfparser_text_pdf', ['admin', 'dpo', 'maker'], 'Text PDF via smalot/pdfparser'],
                ['primary', 'raw_read_text_csv', ['admin', 'dpo', 'maker'], 'TXT/CSV raw read'],
                ['fallback', 'visual_when_short', ['admin', 'dpo', 'maker'], 'If primary <100 chars, try vision'],
                ['fallback', 'provider_resolution', ['admin', 'dpo', 'maker'], 'Active document provider (DeepSeek-OCR/VL2)'],
                ['fallback', 'graceful_degradation', ['admin', 'dpo', 'maker'], 'Vision fail → return primary; never throw'],
                ['confidence', 'tesseract_score', ['admin', 'dpo', 'maker'], 'OCR engine confidence'],
                ['confidence', 'visual_0_8', ['admin', 'dpo', 'maker'], 'Vision hardcoded 0.8'],
                ['credit', 'log_attempt', ['system'], 'AiCreditLog when orgId+userId provided'],
                ['file_types', 'unsupported', ['admin', 'dpo', 'maker'], 'Other formats → empty + source=unsupported'],
                ['error', 'tesseract_unavailable', ['admin', 'dpo', 'maker'], 'CLI not installed → fallback'],
            ],
            'voice_tts' => [
                ['synthesize', 'send_text', ['admin', 'dpo', 'maker', 'viewer'], 'POST {text, gender}; audio_base64'],
                ['provider', 'openai_tts', ['admin', 'dpo', 'maker', 'viewer'], 'tts-1, tts-1-hd; nova/onyx voices'],
                ['provider', 'elevenlabs', ['admin', 'dpo', 'maker', 'viewer'], 'eleven_v3 + premade voices'],
                ['provider', 'google_tts', ['admin', 'dpo', 'maker', 'viewer'], 'WaveNet/Neural2; SSML id-ID'],
                ['provider', 'azure_tts', ['admin', 'dpo', 'maker', 'viewer'], 'GadisNeural/ArdiNeural'],
                ['provider', 'minimax', ['admin', 'dpo', 'maker', 'viewer'], 'speech-02-turbo presets'],
                ['fallback', 'browser_tts', ['admin', 'dpo', 'maker', 'viewer'], 'No provider → fallback=true'],
                ['fallback', 'api_failure_graceful', ['admin', 'dpo', 'maker', 'viewer'], '200 with fallback flag'],
                ['config', 'org_then_global', ['system'], 'Tenant first, fallback global'],
                ['error', 'invalid_gender_422', ['admin', 'dpo', 'maker', 'viewer'], 'gender not male/female'],
            ],
            'avatar_chat' => [
                ['chat', 'send_message', ['admin', 'dpo', 'maker', 'viewer'], 'Chat with 3D avatar (Priva)'],
                ['chat', 'kb_search_top3', ['admin', 'dpo', 'maker', 'viewer'], 'Top 3 KB sections via similarity'],
                ['chat', 'strict_system_prompt', ['system'], 'Platform Q&A only; no AI internals'],
                ['chat', 'response_cleaning', ['system'], 'Strip markdown blocks/inline/bold/italic'],
                ['chat', 'voice_integration', ['admin', 'dpo', 'maker', 'viewer'], 'Response → Voice TTS'],
                ['provider_chain', 'avatar_to_chat_to_agent', ['system'], 'avatar → chat → agent fallback'],
                ['model', 'priva_avatar', ['admin', 'dpo', 'maker', 'viewer'], 'Priva avatar selection'],
                ['model', 'priva_esteh', ['admin', 'dpo', 'maker', 'viewer'], 'Priva Esteh avatar'],
                ['model', 'priva_edmuku', ['admin', 'dpo', 'maker', 'viewer'], 'Priva Edmuku avatar'],
                ['feature', 'lip_sync', ['admin', 'dpo', 'maker', 'viewer'], 'WebGL VRM mouth sync to TTS'],
                ['feature', 'speech_to_text', ['admin', 'dpo', 'maker', 'viewer'], 'Browser STT → chat'],
                ['error', 'graceful_200', ['admin', 'dpo', 'maker', 'viewer'], 'Errors return 200 with error flag'],
            ],
            'log_analyzer' => [
                ['analyze', 'analyze_logs', ['root'], 'AI analyze last ~100 lines laravel.log'],
                ['analyze', 'lock_30s', ['root'], 'Cache lock prevents duplicate proxy timeouts'],
                ['analyze', 'history', ['root'], 'List past analyses paginated'],
                ['status', 'response_codes', ['root'], 'sehat / peringatan / kritis'],
                ['error', 'missing_log_404', ['root'], '404 if log file missing'],
                ['error', 'lock_timeout_429', ['root'], '429 if running'],
                ['error', 'ai_failure_500', ['root'], '500 on parse failure; raw stored'],
            ],
        ];
    }

    private function rootSystem(): array
    {
        return [
            'license_management' => [
                ['license', 'view_all_orgs', ['root', 'superadmin'], 'View all org licenses'],
                ['license', 'view_own_org', ['admin'], 'Own org license only'],
                ['license', 'assign_to_tenant', ['root', 'superadmin'], 'Assign license key to org'],
                ['license', 'activate_via_manager', ['root', 'superadmin', 'admin'], 'License Manager verification'],
                ['license', 'extend_duration', ['root', 'superadmin'], 'Update duration_days'],
                ['license', 'upgrade_package', ['root', 'superadmin'], 'basic → pro/ai/ai_agent'],
                ['license', 'downgrade_package', ['root', 'superadmin'], 'Downgrade reduces features'],
                ['license', 'revoke_with_password', ['root', 'superadmin'], 'Revoke requires password confirm'],
                ['license', 'view_activations', ['root', 'superadmin'], 'LicenseActivation per key'],
                ['license', 'verify_signature', ['root', 'superadmin', 'admin'], 'verify() checks signature + expiry'],
                ['license', 'manage_pricing', ['root', 'superadmin'], 'Per-package tier pricing'],
                ['license', 'soft_delete', ['root', 'superadmin'], 'Soft delete'],
                ['license', 'restore', ['root', 'superadmin'], 'Restore'],
                ['license', 'expiry_scan_daily', ['system'], 'ScanLicenseExpiry command 30/14/7/3/1d/0d'],
            ],
            'tenant_provisioning' => [
                ['isolation', 'list_tenants', ['root', 'superadmin'], 'Filter by state/provider/search'],
                ['isolation', 'view_detail', ['root', 'superadmin'], 'Show config masked, pool name'],
                ['isolation', 'provision_to_pool', ['root', 'superadmin'], 'Dispatch ProvisionTenantDatabaseJob'],
                ['isolation', 'auto_select_pool', ['root', 'superadmin'], 'findActivePool() with capacity'],
                ['isolation', 'migrate_shared_to_isolated', ['root', 'superadmin'], 'Freeze→copy→verify→cutover'],
                ['isolation', 'poll_status', ['root', 'superadmin'], 'state + error messages'],
                ['isolation', 'reset_failed_state', ['root', 'superadmin'], 'Revert to shared, allow retry'],
                ['isolation', 'state_transitions', ['root', 'superadmin'], 'shared → provisioning → isolated/failed'],
                ['cli', 'provision_command', ['system'], 'tenants:provision <org-id>'],
                ['cli', 'migrate_command', ['system'], 'tenants:migrate-data <org-id>'],
                ['pool', 'view_pool_details', ['root', 'superadmin'], 'Pool capacity/engine/region'],
            ],
            'tenant_lifecycle' => [
                ['lifecycle', 'freeze_tenant', ['root', 'superadmin'], 'lifecycle_status=frozen'],
                ['lifecycle', 'unfreeze', ['root', 'superadmin'], 'Restore active'],
                ['lifecycle', 'transfer_ownership', ['root', 'superadmin'], 'Rename + swap admin (password)'],
                ['lifecycle', 'archive_with_retention', ['root', 'superadmin'], 'hard_delete_at +30d default'],
                ['lifecycle', 'view_status', ['root', 'superadmin', 'admin'], 'active/frozen/transferred/archived'],
                ['lifecycle', 'audit_transitions', ['system'], 'AuditLog frozen/unfrozen/transferred/archived'],
            ],
            'menu_registry' => [
                ['layer1_whitelist', 'view_all_menu_items', ['root', 'superadmin', 'admin'], 'Read-only for all'],
                ['layer1_whitelist', 'toggle_menu_per_role', ['root'], 'Root-only: hide menus from any role'],
                ['layer2_entitlement', 'view_matrix', ['root'], 'Paginated org × menu grid'],
                ['layer2_entitlement', 'set_entitlement', ['root'], 'is_entitled + valid_until + notes'],
                ['layer2_entitlement', 'bulk_apply', ['root'], 'Same config to many orgs'],
                ['layer2_entitlement', 'copy_config', ['root'], 'Clone source org → target orgs'],
                ['layer3_override', 'view_override_scope', ['root', 'superadmin', 'admin'], 'Scoped consensus or own'],
                ['layer3_override', 'toggle_visibility', ['root', 'superadmin', 'admin'], 'Per-role within scope'],
                ['layer3_override', 'bulk_global', ['root', 'superadmin'], 'Apply globally if superadmin'],
                ['license_gate', 'package_gate', ['system'], 'required_packages must match License package_type'],
                ['license_gate', 'superadmin_bypass', ['root', 'superadmin'], 'superadmin bypass package gate'],
                ['audit', 'menu_changes_logged', ['root'], 'Whitelist/entitlement/override updates'],
            ],
            'system_settings' => [
                ['infrastructure', 'view_masked', ['root', 'superadmin'], 'Encrypted shown as ***'],
                ['infrastructure', 'configure_hosting_tier', ['root', 'superadmin'], 'shared/dedicated/multi-region'],
                ['infrastructure', 'configure_queue_driver', ['root', 'superadmin'], 'sync/database/redis/sqs'],
                ['infrastructure', 'configure_sqs', ['root', 'superadmin'], 'Access key, secret, region, URL'],
                ['infrastructure', 'test_sqs', ['root', 'superadmin'], 'GetQueueAttributes validates'],
                ['redis', 'configure', ['root', 'superadmin'], 'host/port/password (encrypted)'],
                ['redis', 'test_ping', ['root', 'superadmin'], 'PING via one-off connection'],
                ['mail', 'configure_smtp', ['root', 'superadmin'], 'host/port/user/pass (encrypted)'],
                ['mail', 'test_smtp_handshake', ['root', 'superadmin'], 'EHLO + AUTH no test email'],
                ['ai', 'enable_jobs', ['root', 'superadmin'], 'ai.jobs_enabled boolean'],
                ['ai', 'set_local_llm_url', ['root', 'superadmin'], 'For on-prem'],
                ['ai', 'max_concurrent_per_user', ['root', 'superadmin'], 'Concurrency limit'],
                ['ai', 'history_retention_days', ['root', 'superadmin'], 'Cleanup interval'],
                ['deployment', 'set_mode', ['root', 'superadmin'], 'production/staging/development'],
                ['cache', 'file_cache_invalidation', ['system'], 'system_settings.json on save'],
                ['audit', 'log_section_updates', ['system'], 'Every section update logged'],
            ],
            'system_update' => [
                ['backend', 'check_updates', ['root'], 'git fetch; list pending commits'],
                ['backend', 'view_history', ['root'], 'Installed commits via git log'],
                ['backend', 'apply_updates', ['root'], 'pull → composer → migrate → optimize'],
                ['backend', 'checkout_version', ['root'], 'Revert to commit (within last 10, password)'],
                ['frontend', 'check_status', ['root'], 'Mode (shell/webhook), path, npm avail'],
                ['frontend', 'deploy_shell', ['root'], 'pull → npm ci → build → reload'],
                ['frontend', 'deploy_webhook', ['root'], 'Trigger via configured URL'],
                ['frontend', 'view_deployment_logs', ['root'], 'Git/composer/build/reload output'],
            ],
            'audit_log' => [
                ['list', 'all_entries', ['root', 'superadmin'], 'Module/action/role/created_at'],
                ['list', 'own_org_only', ['admin'], 'Admin scoped to own org'],
                ['filter', 'by_user_module_action', ['root', 'superadmin', 'admin'], 'Multiple filters'],
                ['filter', 'by_ip_date_range', ['root', 'superadmin', 'admin'], 'Search by IP/date'],
                ['view', 'change_history', ['root', 'superadmin', 'admin'], 'Encrypted fields masked'],
                ['export', 'export_csv', ['root', 'superadmin', 'admin'], 'CSV download'],
            ],
            'notifications' => [
                ['prefs', 'list_user_prefs', ['admin', 'dpo', 'maker', 'viewer'], 'Per-user digest/channel/module'],
                ['prefs', 'update_prefs', ['admin', 'dpo', 'maker', 'viewer'], 'Update rules'],
                ['prefs', 'reset_defaults', ['admin', 'dpo', 'maker', 'viewer'], 'Revert to platform defaults'],
                ['prefs', 'set_digest_frequency', ['admin', 'dpo', 'maker', 'viewer'], 'immediate/daily/weekly/never'],
                ['prefs', 'choose_channel', ['admin', 'dpo', 'maker', 'viewer'], 'email/in-app/whatsapp'],
                ['prefs', 'filter_by_module', ['admin', 'dpo', 'maker', 'viewer'], 'Per-module filter'],
                ['system', 'enable_globally', ['root', 'superadmin'], 'Kill switch in settings'],
                ['system', 'manual_dispatch', ['root', 'superadmin'], 'NotificationService::dispatch()'],
                ['scheduler', 'daily_digest', ['system'], 'SendNotificationDigest cron'],
                ['scheduler', 'license_expiry_scan', ['system'], 'ScanLicenseExpiry windows'],
                ['scheduler', 'rule_scan_per_org', ['system'], 'ScanAllNotificationRules'],
                ['unsubscribe', 'email_footer_url', ['admin', 'dpo', 'maker', 'viewer'], 'Signed URL one-click unsub'],
            ],
            'tenant_roles' => [
                ['list', 'all_orgs', ['root', 'superadmin'], 'Filter by ?org_id=, user count'],
                ['list', 'own_org', ['admin'], 'Admin scoped'],
                ['detail', 'view_permissions', ['root', 'superadmin', 'admin'], 'Permissions JSON array'],
                ['create', 'requires_perpetual', ['root', 'superadmin', 'admin'], 'Custom roles only on perpetual'],
                ['create', 'set_permissions_array', ['root', 'superadmin', 'admin'], 'permissions JSON or *'],
                ['edit', 'modify_permissions', ['root', 'superadmin', 'admin'], 'Update name/desc/permissions'],
                ['delete', 'block_if_assigned', ['root', 'superadmin', 'admin'], 'Cannot delete if users assigned'],
                ['delete', 'system_roles_protected', ['root', 'superadmin', 'admin'], 'System roles cannot be deleted'],
                ['assign', 'set_user_role', ['root', 'superadmin', 'admin'], 'tenant_role_id → custom permissions'],
            ],
            'user_management' => [
                ['list', 'all_orgs', ['root', 'superadmin'], 'Filter by ?org_id'],
                ['list', 'own_plus_descendants', ['admin'], 'Admin descendant scope'],
                ['create', 'with_role', ['root', 'superadmin', 'admin'], 'Auto-assign tenant_role_id'],
                ['create', 'auto_create_org', ['root', 'superadmin', 'admin'], 'role=admin without org_id → create org'],
                ['detail', 'view_user', ['root', 'superadmin', 'admin'], 'View own org + children'],
                ['update', 'profile_fields', ['root', 'superadmin', 'admin'], 'Name/email/password/phone/position'],
                ['update', 'change_role', ['root', 'superadmin', 'admin'], 'Update tenant_role_id'],
                ['update', 'change_org', ['root', 'superadmin', 'admin'], 'Move user between orgs (descendants)'],
                ['update', 'restructure_hierarchy', ['root', 'superadmin', 'admin'], 'Update org level/parent'],
                ['action', 'reset_password', ['root', 'superadmin', 'admin'], 'Set new password directly'],
                ['action', 'soft_delete_not_self', ['root', 'superadmin', 'admin'], 'Cannot delete self'],
                ['action', 'restore', ['root', 'superadmin', 'admin'], 'Reactivate'],
                ['action', 'deactivate_toggle', ['root', 'superadmin', 'admin'], 'is_active toggle'],
                ['system', 'seed_notification_prefs', ['system'], 'Auto on user creation per role'],
            ],
            'organization' => [
                ['list', 'with_hierarchy', ['root', 'superadmin'], 'Parent ref, user count, children'],
                ['list', 'descendants_only', ['admin'], 'Admin scoped'],
                ['detail', 'view_org', ['root', 'superadmin', 'admin'], 'All fields'],
                ['create', 'auto_on_admin_promo', ['root', 'superadmin', 'admin'], 'Promote user → create org'],
                ['update', 'basic_fields', ['root', 'superadmin', 'admin'], 'name/industry/logo/website/address/phone/email'],
                ['update', 'idle_timeout', ['root', 'superadmin', 'admin'], 'Per-org idle timeout settings'],
                ['update', 'onboarding_fields', ['root', 'superadmin', 'admin'], 'business_model/company_size/data_subjects'],
                ['update', 'onboarding_completed', ['root', 'superadmin', 'admin'], 'Mark complete to unlock modules'],
                ['hierarchy', 'set_org_level', ['root', 'superadmin', 'admin'], 'holding/sub_holding/subsidiary'],
                ['hierarchy', 'set_parent_id', ['root', 'superadmin', 'admin'], 'Hierarchy restructuring'],
                ['action', 'deactivate_with_pwd', ['root', 'superadmin', 'admin'], 'Requires password confirm'],
                ['view', 'with_trashed', ['root', 'superadmin'], 'Include archived orgs'],
                ['white_label', 'configure_settings', ['root', 'superadmin', 'admin'], 'Logo/colors/domain/policy URL'],
            ],
            'auth_sso' => [
                ['manual', 'register', ['public'], 'Auto-create org + admin + token'],
                ['manual', 'login', ['public'], 'Email/password + is_active check'],
                ['manual', 'logout', ['admin', 'dpo', 'maker', 'viewer'], 'Token revocation'],
                ['manual', 'check_me', ['admin', 'dpo', 'maker', 'viewer'], 'Returns user + license info'],
                ['manual', 'password_reset', ['public'], 'Email token validation'],
                ['sso', 'configure_provider', ['root'], 'Azure AD / Keycloak via SocialiteProviders'],
                ['sso', 'set_credentials', ['root'], 'Client ID/secret/endpoints'],
                ['sso', 'callback_handling', ['system'], 'SsoLoginController maps external → local'],
                ['idle', 'configure_per_org', ['root', 'superadmin', 'admin'], 'idle_timeout_minutes'],
                ['idle', 'enforce_auto_logout', ['system'], 'Frontend polls /me; backend tracks activity'],
            ],
            'partner_api' => [
                ['key', 'generate_key', ['root', 'superadmin'], 'Authenticated via AuthenticatePartnerApi'],
                ['key', 'revoke', ['root', 'superadmin'], 'Deactivate partner integration'],
                ['key', 'view_usage_logs', ['root', 'superadmin'], 'Calls per partner/endpoint/codes'],
                ['key', 'rate_limits', ['root', 'superadmin'], 'Requests/min per partner'],
                ['breach_v1', 'partner_breach_api', ['public'], 'BreachApiController for partners'],
                ['consent_v1', 'consent_v1_api', ['public'], 'ConsentApiV1Controller via app key'],
                ['dsr_v1', 'dsr_v1_api', ['public'], 'DsrApiV1Controller via app key'],
            ],
            'voice_avatar_provider_admin' => [
                ['tts', 'configure_provider', ['root'], 'Google/Azure/OpenAI/ElevenLabs/MiniMax'],
                ['tts', 'set_credentials', ['root'], 'API key/region/lang'],
                ['avatar', 'configure_provider', ['root'], 'Synthesia/D-ID/custom'],
                ['avatar', 'set_credentials', ['root'], 'API key/model ID/quality'],
                ['both', 'test_generation', ['root'], 'Sample output to verify'],
                ['both', 'assign_to_org', ['root'], 'Org-level provider assignment'],
            ],
            'feature_requests' => [
                ['public', 'submit_request', ['public'], 'From landing page'],
                ['admin', 'list_requests', ['root', 'superadmin'], 'Filter by status/priority/category'],
                ['admin', 'update_status', ['root', 'superadmin'], 'backlog → in_progress → completed → archived'],
                ['admin', 'set_priority', ['root', 'superadmin'], 'low/medium/high/critical'],
                ['admin', 'assign_developer', ['root', 'superadmin'], 'Link to internal task'],
            ],
            'public_landing_cms' => [
                ['cms', 'edit_hero', ['root', 'superadmin'], 'Title/subtitle/CTA/bg'],
                ['cms', 'manage_features', ['root', 'superadmin'], 'Description/icon/order'],
                ['cms', 'update_pricing', ['root', 'superadmin'], 'Plans + features per plan'],
                ['cms', 'manage_faq', ['root', 'superadmin'], 'Q&A pairs'],
                ['cms', 'upload_assets', ['root', 'superadmin'], 'Logo/hero/icons'],
                ['cms', 'preview_draft', ['root', 'superadmin'], 'Draft state'],
                ['cms', 'publish', ['root', 'superadmin'], 'Invalidate cache + go live'],
            ],
        ];
    }

    private function userFacing(): array
    {
        return [
            'onboarding' => [
                ['org_setup', 'business_model', ['admin'], 'startup/smb/enterprise/nonprofit'],
                ['org_setup', 'company_size', ['admin'], '1-10/11-50/51-500/500+'],
                ['org_setup', 'data_subjects_type', ['admin'], 'employees/customers/suppliers/citizens/patients/students'],
                ['org_setup', 'core_systems', ['admin'], 'CRM/HRIS/ERP/Accounting/Email/Docs/Analytics/Database/Website'],
                ['org_setup', 'has_dpo_toggle', ['admin'], 'DPO checkbox'],
                ['org_setup', 'mark_completed', ['admin'], 'Unlock all modules'],
            ],
            'dashboard_analytics' => [
                ['stats', 'view_gap_score', ['admin', 'dpo', 'maker', 'viewer'], 'GAP score + level + progress'],
                ['stats', 'view_module_counts', ['admin', 'dpo', 'maker', 'viewer'], 'RoPA/DPIA/DSR/Breach/Consent counts'],
                ['stats', 'view_dsr_pending', ['admin', 'dpo', 'maker', 'viewer'], 'Pending + overdue'],
                ['stats', 'view_active_breaches', ['admin', 'dpo', 'maker', 'viewer'], 'Non-closed breaches'],
                ['stats', 'view_data_sources', ['admin', 'dpo', 'maker', 'viewer'], 'Total information systems'],
                ['charts', 'monthly_trend', ['admin', 'dpo', 'maker', 'viewer'], '5-module line chart 7mo'],
                ['charts', 'gap_history', ['admin', 'dpo', 'maker', 'viewer'], 'Last 20 GAP scores'],
                ['charts', 'ropa_by_status', ['admin', 'dpo', 'maker', 'viewer'], 'Bar by status'],
                ['charts', 'dpia_by_risk', ['admin', 'dpo', 'maker', 'viewer'], 'Bar by risk_level'],
                ['charts', 'dsr_by_type', ['admin', 'dpo', 'maker', 'viewer'], 'Bar by request_type'],
                ['charts', 'breach_by_severity', ['admin', 'dpo', 'maker', 'viewer'], 'Bar by severity'],
                ['risk_analytics', 'ropa_by_risk_level', ['admin', 'dpo', 'maker', 'viewer'], 'KPI grid'],
                ['risk_analytics', 'top_10_risks_table', ['admin', 'dpo', 'maker', 'viewer'], 'Top RoPA by risk'],
                ['risk_analytics', 'dpia_heatmap', ['admin', 'dpo', 'maker', 'viewer'], 'Likelihood × impact 2D'],
                ['risk_analytics', 'unmitigated_dpia', ['admin', 'dpo', 'maker', 'viewer'], 'Score≥12 unmitigated'],
                ['risk_analytics', 'dsr_response_times', ['admin', 'dpo', 'maker', 'viewer'], 'Avg days/month'],
                ['risk_analytics', 'breach_timeline', ['admin', 'dpo', 'maker', 'viewer'], 'Recent 8 breaches'],
                ['risk_analytics', 'consent_adoption', ['admin', 'dpo', 'maker', 'viewer'], 'Acceptance rate %/month'],
            ],
            'profile_settings' => [
                ['profile', 'update_name', ['admin', 'dpo', 'maker', 'viewer'], 'Encrypted full name'],
                ['profile', 'update_email', ['admin', 'dpo', 'maker', 'viewer'], 'Work email'],
                ['profile', 'update_phone', ['admin', 'dpo', 'maker', 'viewer'], 'Encrypted phone'],
                ['profile', 'upload_avatar', ['admin', 'dpo', 'maker', 'viewer'], 'PNG/JPG'],
                ['profile', 'set_position', ['admin', 'dpo', 'maker', 'viewer'], 'LazySearchSelect /positions'],
                ['profile', 'select_department', ['admin', 'dpo', 'maker', 'viewer'], 'Org hierarchy'],
                ['locale', 'switch_language', ['admin', 'dpo', 'maker', 'viewer'], 'id / en'],
                ['idle_timeout', 'configure_minutes', ['admin'], 'Per-org enabled + minutes'],
                ['password', 'change_password', ['admin', 'dpo', 'maker', 'viewer'], 'Current + new'],
            ],
            'white_label_theme' => [
                ['theme', 'list_themes', ['admin', 'dpo'], 'Active/draft themes'],
                ['theme', 'create_manual', ['admin', 'dpo'], 'Set palette colors'],
                ['theme', 'create_ai_generated', ['admin', 'dpo'], 'AI generates palette+gradient+radius+shadow'],
                ['theme', 'edit_theme', ['admin', 'dpo'], 'Name/palette/layout_preset/font/logo/favicon'],
                ['theme', 'set_active', ['admin', 'dpo'], 'Activate (deactivate others)'],
                ['theme', 'deactivate', ['admin', 'dpo'], 'Without activating another'],
                ['theme', 'use_default', ['admin', 'dpo'], 'Revert to built-in CSS'],
                ['theme', 'export_json', ['admin', 'dpo'], 'For sharing across holding'],
                ['theme', 'import_json', ['admin', 'dpo'], 'Import as draft'],
                ['theme', 'upload_logo', ['admin', 'dpo'], 'Tenant storage'],
                ['theme', 'upload_favicon', ['admin', 'dpo'], 'Set favicon_url'],
                ['theme', 'limit_3_per_org', ['admin', 'dpo'], 'Max 3 themes (legacy editing always allowed)'],
            ],
            'custom_wizard' => [
                ['master_schema', 'fetch_merged', ['admin', 'dpo', 'maker', 'viewer'], 'Built-in + custom merged in order'],
                ['master_schema', 'inspect_builtin', ['admin', 'dpo', 'maker', 'viewer'], 'Read-only standard fields'],
                ['master_schema', 'inspect_custom_fields_in_builtin', ['admin', 'dpo', 'maker', 'viewer'], 'Org custom fields in built-in step'],
                ['master_schema', 'inspect_custom_sections', ['admin', 'dpo', 'maker', 'viewer'], 'Custom sections as full steps'],
                ['custom_field', 'add_global_in_builtin', ['admin', 'dpo'], 'Add to built-in step'],
                ['custom_field', 'edit_label', ['admin', 'dpo'], 'Rename'],
                ['custom_field', 'edit_type', ['admin', 'dpo'], 'text/textarea/number/date/boolean/select/multiselect/tags'],
                ['custom_field', 'edit_options', ['admin', 'dpo'], 'Add/edit/remove select options'],
                ['custom_field', 'toggle_required', ['admin', 'dpo'], 'is_required'],
                ['custom_field', 'set_help_text', ['admin', 'dpo'], 'Tooltip'],
                ['custom_field', 'reorder_within_section', ['admin', 'dpo'], 'Drag-drop sort_order'],
                ['custom_field', 'delete_with_warning', ['admin', 'dpo'], 'Soft delete + warn data hidden'],
                ['custom_section', 'add_full_step', ['admin', 'dpo'], 'New section as wizard step'],
                ['custom_section', 'reorder', ['admin', 'dpo'], 'Drag-drop section order'],
                ['custom_section', 'edit_section', ['admin', 'dpo'], 'Edit label + description'],
                ['custom_section', 'delete_section', ['admin', 'dpo'], 'Soft delete + all fields'],
                ['custom_section', 'toggle_active', ['admin', 'dpo'], 'Disable without deleting'],
                ['per_record_extras', 'add_ad_hoc_field', ['admin', 'dpo', 'maker'], 'Field not in master schema'],
                ['per_record_extras', 'edit_value', ['admin', 'dpo', 'maker'], 'Edit per-record value'],
                ['per_record_extras', 'delete_field', ['admin', 'dpo', 'maker'], 'Remove from this record only'],
            ],
            'departments_positions' => [
                ['dept', 'list', ['admin', 'dpo', 'maker', 'viewer'], 'Hierarchy + head + counts'],
                ['dept', 'create', ['admin', 'dpo'], 'Name/code/parent/head/description'],
                ['dept', 'edit', ['admin', 'dpo'], 'Toggle is_active'],
                ['dept', 'delete', ['admin', 'dpo'], 'Soft delete'],
                ['dept', 'view_tree', ['admin', 'dpo', 'maker', 'viewer'], 'Visual hierarchy'],
                ['position', 'list', ['admin', 'dpo', 'maker', 'viewer'], 'With dept association + user count'],
                ['position', 'create', ['admin', 'dpo'], 'Name/department/level/description'],
                ['position', 'edit', ['admin', 'dpo'], 'Toggle is_active'],
                ['position', 'delete', ['admin', 'dpo'], 'Soft delete'],
                ['dpo_users', 'fetch_picker', ['admin', 'dpo', 'maker'], 'DPO+admin filtered list for RoPA/DPIA'],
            ],
            'comments' => [
                ['comments', 'fetch_record_thread', ['admin', 'dpo', 'maker', 'viewer'], 'Threaded tree per record'],
                ['comments', 'add_root', ['admin', 'dpo', 'maker', 'viewer'], 'New comment'],
                ['comments', 'add_reply', ['admin', 'dpo', 'maker', 'viewer'], 'Reply with parent_id'],
                ['comments', 'edit_own', ['admin', 'dpo', 'maker', 'viewer'], 'If author or admin'],
                ['comments', 'edit_admin_override', ['admin'], 'Edit any comment'],
                ['comments', 'delete_own', ['admin', 'dpo', 'maker', 'viewer'], 'Soft delete if author/admin'],
                ['comments', 'paginate', ['admin', 'dpo', 'maker', 'viewer'], '20 per load + scroll'],
                ['comments', 'mention_user', ['admin', 'dpo', 'maker', 'viewer'], '@autocomplete + notify'],
            ],
            'document_archive' => [
                ['contract', 'list', ['admin', 'dpo', 'maker', 'viewer'], 'List with soft-delete filter'],
                ['contract', 'filter_search', ['admin', 'dpo', 'maker', 'viewer'], 'status/date/user/name'],
                ['contract', 'view', ['admin', 'dpo', 'maker', 'viewer'], 'Detail + file preview + analysis'],
                ['contract', 'download_original', ['admin', 'dpo', 'maker'], 'PDF/DOCX'],
                ['contract', 'soft_delete', ['admin', 'dpo'], 'To trash'],
                ['contract', 'restore', ['admin', 'dpo'], 'From trash'],
                ['policy', 'list', ['admin', 'dpo', 'maker', 'viewer'], 'List policy reviews'],
                ['policy', 'filter_search', ['admin', 'dpo', 'maker', 'viewer'], 'status/date/user/doc_type'],
                ['policy', 'view', ['admin', 'dpo', 'maker', 'viewer'], 'Analysis + clauses + gaps'],
                ['policy', 'download', ['admin', 'dpo', 'maker'], 'Download document'],
                ['policy', 'soft_delete', ['admin', 'dpo'], 'To trash'],
                ['policy', 'restore', ['admin', 'dpo'], 'From trash'],
                ['doc_maker', 'list_drafts', ['admin', 'dpo', 'maker'], 'AI-generated drafts'],
                ['doc_maker', 'view_draft', ['admin', 'dpo', 'maker'], 'Sections + placeholders + compliance feedback'],
                ['doc_maker', 'download', ['admin', 'dpo', 'maker'], 'DOCX or PDF'],
                ['doc_maker', 'discard', ['admin', 'dpo', 'maker'], 'Soft delete'],
            ],
            'export_reports' => [
                ['ropa', 'export_csv', ['admin', 'dpo', 'maker'], 'All records + custom fields UTF-8 BOM'],
                ['ropa', 'filter_export', ['admin', 'dpo', 'maker'], 'By status/risk/date'],
                ['dpia', 'export_csv', ['admin', 'dpo', 'maker'], 'All DPIAs'],
                ['dpia', 'export_with_risks', ['admin', 'dpo', 'maker'], 'Include likelihood/impact/mitigation'],
                ['dsr', 'export_csv', ['admin', 'dpo', 'maker', 'viewer'], 'subject/type/status/deadline'],
                ['dsr', 'filter_status', ['admin', 'dpo', 'maker', 'viewer'], 'new/in_progress/completed/overdue'],
                ['breach', 'export_csv', ['admin', 'dpo', 'maker', 'viewer'], 'severity/status/affected_subjects'],
                ['consent', 'export_csv', ['admin', 'dpo', 'maker', 'viewer'], 'Records with decision + collection_point'],
                ['module', 'export_pdf_branded', ['admin', 'dpo', 'maker', 'viewer'], 'PDF with org branding/logo/charts'],
                ['module', 'export_docx', ['admin', 'dpo', 'maker'], 'Modifiable sections + placeholders'],
                ['bulk', 'select_export', ['admin', 'dpo', 'maker'], 'Checkbox + Export selected'],
            ],
            'consent_capture_public' => [
                ['banner_setup', 'generate_js_snippet', ['admin', 'dpo'], 'Configure banner colors/text'],
                ['banner_setup', 'whitelist_domains', ['admin', 'dpo'], 'Allowed embed domains'],
                ['banner_setup', 'set_position', ['admin', 'dpo'], 'bottom-left/center/right'],
                ['banner_setup', 'install_script', ['admin', 'dpo'], 'Embed in website footer'],
                ['banner_setup', 'test_staging', ['admin', 'dpo'], 'Test before prod'],
                ['visitor', 'grant_consent', ['public'], 'Click Accept → recorded'],
                ['visitor', 'deny_consent', ['public'], 'Click Decline → recorded'],
                ['visitor', 'manage_preferences', ['public'], 'Click Preferences → preference-center'],
                ['admin', 'export_consent_log', ['admin', 'dpo', 'maker', 'viewer'], 'Timestamp + IP + user_agent'],
            ],
            'preference_center' => [
                ['load', 'public_page', ['public'], 'Per org branding'],
                ['auth', 'check_email', ['public'], 'Send verification link'],
                ['auth', 'verify_email', ['public'], 'Click link to unlock'],
                ['view', 'list_consents', ['public'], 'Active consent points + decision'],
                ['edit', 'withdraw_consent', ['public'], 'Mark as_granted=false'],
                ['edit', 'grant_consent', ['public'], 'Mark as_granted=true'],
                ['edit', 'save_preferences', ['public'], 'Update consent_records + email'],
                ['embed', 'get_link', ['admin', 'dpo'], 'Embed in privacy page'],
            ],
            'embed_pages' => [
                ['consent_editor', 'load_embed', ['public'], 'Configure on client website'],
                ['consent_editor', 'configure_settings', ['admin', 'dpo'], 'Edit text/colors/buttons'],
                ['consent_editor', 'live_preview', ['admin', 'dpo'], 'Preview within window'],
                ['pref_center', 'load_embed', ['public'], 'iframe widget on client site'],
                ['pref_center', 'manage_within_iframe', ['public'], 'Toggle + save no reload'],
            ],
            'list_filter_pagination' => [
                ['search', 'by_name', ['admin', 'dpo', 'maker', 'viewer'], 'Text search across modules'],
                ['search', 'by_code', ['admin', 'dpo', 'maker', 'viewer'], 'For coded records'],
                ['filter', 'by_status', ['admin', 'dpo', 'maker', 'viewer'], 'Per-module status'],
                ['filter', 'by_risk', ['admin', 'dpo', 'maker', 'viewer'], 'low/medium/high'],
                ['filter', 'by_date_range', ['admin', 'dpo', 'maker', 'viewer'], 'from/to date'],
                ['filter', 'by_assignee', ['admin', 'dpo', 'maker', 'viewer'], 'PIC/assignee'],
                ['filter', 'by_department', ['admin', 'dpo', 'maker', 'viewer'], 'Multi-select'],
                ['paginate', 'per_page', ['admin', 'dpo', 'maker', 'viewer'], '20/50/100'],
                ['paginate', 'goto_page', ['admin', 'dpo', 'maker', 'viewer'], 'Jump to page'],
                ['sort', 'by_column', ['admin', 'dpo', 'maker', 'viewer'], 'Toggle asc/desc'],
                ['bulk', 'select_checkboxes', ['admin', 'dpo', 'maker', 'viewer'], 'Multi-select'],
                ['bulk', 'select_all', ['admin', 'dpo', 'maker', 'viewer'], 'Page-wide select'],
            ],
            'bulk_actions' => [
                ['bulk', 'export_selected_csv', ['admin', 'dpo', 'maker'], 'Export selected'],
                ['bulk', 'soft_delete_selected', ['admin', 'dpo'], 'Move multiple to trash'],
                ['bulk', 'approve_multiple_ropa', ['admin', 'dpo'], 'Approve all (DPO)'],
                ['bulk', 'reject_multiple_ropa', ['admin', 'dpo'], 'Reject all + comment'],
                ['bulk', 'change_status_batch', ['admin', 'dpo', 'maker'], 'Bulk status change'],
                ['bulk', 'assign_multiple', ['admin', 'dpo', 'maker'], 'Same user assignment'],
                ['bulk', 'add_tag_batch', ['admin', 'dpo', 'maker'], 'Add classification tags'],
            ],
            'file_upload' => [
                ['contract', 'select_file', ['admin', 'dpo', 'maker'], 'PDF/DOCX/DOCM drag-drop'],
                ['policy', 'select_file', ['admin', 'dpo', 'maker'], 'Privacy/cookie/policy doc'],
                ['ropa_import', 'upload_csv_batch', ['admin', 'dpo', 'maker'], 'CSV → multiple records'],
                ['dpia_import', 'upload_csv_batch', ['admin', 'dpo', 'maker'], 'CSV → DPIA records'],
                ['breach_evidence', 'attach_files', ['admin', 'dpo', 'maker'], 'Forensic logs/screenshots'],
                ['breach_evidence', 'versioning', ['admin', 'dpo', 'maker'], 'Timestamped versions'],
                ['dsr_identity', 'upload_id', ['admin', 'dpo', 'maker'], 'Encrypted ID upload'],
                ['dsr_identity', 'ocr_extract', ['admin', 'dpo', 'maker'], 'Auto-fill from ID OCR'],
                ['avatar', 'change_avatar', ['admin', 'dpo', 'maker', 'viewer'], 'Profile avatar'],
                ['avatar', 'crop_rotate', ['admin', 'dpo', 'maker', 'viewer'], 'Crop before save'],
                ['template', 'upload_docx', ['admin', 'dpo'], 'Document template with {{ placeholders }}'],
                ['template', 'parse_placeholders', ['admin', 'dpo'], 'Auto-extract available fields'],
                ['dpia', 'import_from_ropa', ['admin', 'dpo', 'maker'], 'Auto-populate from RoPA record'],
            ],
            'settings_flat_page' => [
                ['org', 'edit_org_info', ['admin'], 'Name/industry/website/email/phone/address'],
                ['org', 'upload_logo', ['admin'], 'Branding logo'],
                ['org', 'set_privacy_url', ['admin'], 'External policy URL'],
                ['org', 'select_active_theme', ['admin'], 'Active theme'],
                ['idle', 'enable_idle_logout', ['admin'], 'Toggle'],
                ['idle', 'set_minutes', ['admin'], '5-240 minutes'],
                ['ai', 'configure_providers', ['admin'], 'Select + API keys'],
                ['ai', 'test_connections', ['admin'], 'Per-provider test'],
                ['automation', 'dsr_auto_draft', ['admin'], 'Toggle DSR auto-draft AI'],
                ['automation', 'dpia_auto_trigger', ['admin'], 'Auto-create DPIA on RoPA high'],
                ['automation', 'consent_reminder', ['admin'], 'Toggle expiry reminder'],
                ['automation', 'consent_reminder_days', ['admin'], 'Days before expiry'],
                ['automation', 'scan_reminder', ['admin'], 'Remind to scan old systems'],
                ['save', 'per_section_save', ['admin'], 'Independent Save per section'],
                ['save', 'success_toast', ['admin'], 'Confirmation after save'],
                ['departments', 'manage_in_settings', ['admin', 'dpo'], 'CRUD'],
                ['positions', 'manage_in_settings', ['admin', 'dpo'], 'CRUD'],
                ['raci_templates', 'manage_in_settings', ['admin', 'dpo'], 'View/edit/create templates'],
                ['retention', 'manage_in_settings', ['admin', 'dpo'], 'Retention master data'],
            ],
            'cookie_management' => [
                ['point', 'create_collection_point', ['admin', 'dpo'], 'Per website/app'],
                ['point', 'configure_banner', ['admin', 'dpo'], 'Template choice + customization'],
                ['point', 'select_template', ['admin', 'dpo'], 'basic/GDPR/lightweight/full'],
                ['point', 'customize_template', ['admin', 'dpo'], 'Text/colors/buttons'],
                ['point', 'generate_js_snippet', ['admin', 'dpo'], 'Embed code'],
                ['log', 'capture_visitor', ['public'], 'Visitor decisions logged'],
                ['log', 'export_decisions', ['admin', 'dpo', 'maker', 'viewer'], 'CSV export of cookie consent'],
            ],
            'qa_center' => [
                ['cases', 'list_catalog', ['root'], 'List all test cases (built-in + custom)'],
                ['cases', 'create_custom_case', ['root'], 'Add tester-defined case'],
                ['cases', 'edit_case', ['root'], 'Edit title/description/roles'],
                ['cases', 'toggle_active', ['root'], 'Hide built-in via is_active=false'],
                ['cases', 'delete_custom', ['root'], 'Delete custom case (built-in protected)'],
                ['runs', 'create_run', ['root'], 'Create QA cycle; auto-seed results'],
                ['runs', 'list_runs', ['root'], 'Active/closed/archived'],
                ['runs', 'show_with_stats', ['root'], 'Stats: pass/fail/blocked/not_tested + bug count'],
                ['runs', 'update_status', ['root'], 'active → closed → archived'],
                ['runs', 'soft_delete_run', ['root'], 'Trash a run'],
                ['runs', 'restore_run', ['root'], 'Restore from trash'],
                ['runs', 'force_delete', ['root'], 'Permanent delete'],
                ['results', 'list_per_run', ['root'], 'Filter by module/role/status'],
                ['results', 'update_status', ['root'], 'pass/fail/blocked/skip/na + tester + tested_at'],
                ['bugs', 'create_from_failed_result', ['root'], 'Auto-link to result; severity'],
                ['bugs', 'list_bugs', ['root'], 'Filter by status/severity/run/module'],
                ['bugs', 'update_status', ['root'], 'open → in_progress → fixed/wontfix → verified'],
                ['bugs', 'auto_resolved_at', ['root'], 'Auto-stamp on fixed/wontfix'],
                ['bugs', 'auto_verified_at', ['root'], 'Auto-stamp on verified'],
                ['bugs', 'soft_delete', ['root'], 'Delete bug report'],
                ['screenshots', 'upload_image', ['root'], 'JPG/PNG/GIF/WEBP max 8MB'],
                ['screenshots', 'download', ['root'], 'Download original'],
                ['screenshots', 'delete', ['root'], 'Remove + cleanup file'],
                ['dashboard', 'aggregate_stats', ['root'], 'Status counts + per-module breakdown + bug stats'],
            ],
        ];
    }
}
