<?php

namespace App\Services;

use App\Models\DataDiscoveryScanPlan;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

/**
 * Person Scan SaaS pack builder — mirrors DsrSqlGeneratorService pattern.
 *
 * INVARIANT: Privasimu does NOT execute SQL on the tenant DB in SaaS mode.
 * This service produces a downloadable ZIP that the tenant DBA executes
 * manually against a read replica, then uploads results back via the upload
 * endpoint. SQL files have parameters substituted as quoted literals (most
 * DBAs paste-and-run rather than wire prepared statements through a CLI).
 *
 * Output structure:
 *   scan-pack-{plan_id}.zip
 *   ├── README.md
 *   ├── manifest.json
 *   ├── 01_{App_Name}__{table_name}.sql
 *   ├── 02_...
 *   └── result_template.csv
 *
 * See DATA_DISCOVERY_SEARCH_PLAN.md §6.2.
 */
class DataDiscoveryScanPackService
{
    private const PRIVASIMU_HEADER_LINES = [
        '-- ╔══════════════════════════════════════════════════════════════════╗',
        '-- ║              GENERATED BY PRIVASIMU NEXUS                       ║',
        '-- ║         Person Scan — Cross-App PII Discovery Pack               ║',
        '-- ╚══════════════════════════════════════════════════════════════════╝',
    ];

    /**
     * Build the ZIP and persist it under the org's private storage. Returns
     * the relative storage path which the controller stores on the plan and
     * later streams via Storage::disk('local')->download().
     */
    public function buildZip(DataDiscoveryScanPlan $plan): string
    {
        $plan->loadMissing('planSystems.informationSystem');

        $files = [];
        $manifestScopes = [];
        $fileSeq = 1;
        $totalTables = 0;

        foreach ($plan->planSystems as $ps) {
            $appCode = $this->slugify($ps->app_name ?: 'APP');
            foreach (($ps->table_queries ?? []) as $q) {
                $tableName = $q['table'] ?? 'unknown';
                $filename = sprintf('%02d_%s__%s.sql', $fileSeq, $appCode, $this->slugify($tableName));
                $files[$filename] = $this->buildSqlFile($plan, $ps->app_name, $q);
                $manifestScopes[] = [
                    'file' => $filename,
                    'app_name' => $ps->app_name,
                    'table' => $tableName,
                    'confidence' => $q['confidence'] ?? 'unknown',
                    'matched_columns' => $q['matched_columns'] ?? [],
                    'plan_system_id' => $ps->id,
                ];
                $fileSeq++;
                $totalTables++;
            }
        }

        $manifest = [
            'plan_id' => $plan->id,
            'org_id' => $plan->org_id,
            'label' => $plan->label,
            'identifiers_masked' => $plan->identifiers,
            'total_systems' => $plan->total_systems,
            'total_tables' => $totalTables,
            'generated_at' => now()->toIso8601String(),
            'expires_at' => $plan->expires_at?->toIso8601String(),
            'scopes' => $manifestScopes,
        ];

        $files['manifest.json'] = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        $files['README.md'] = $this->buildReadme($plan, $manifest);
        $files['result_template.csv'] = $this->buildResultTemplate($plan);

        $relPath = sprintf('scan-packs/%s/%s.zip', $plan->org_id, $plan->id);
        $tmpZip = tempnam(sys_get_temp_dir(), 'scan-pack-');
        $zip = new ZipArchive;
        if ($zip->open($tmpZip, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Cannot create scan pack ZIP at '.$tmpZip);
        }
        foreach ($files as $name => $body) {
            $zip->addFromString($name, $body);
        }
        $zip->close();

        Storage::disk('local')->put($relPath, file_get_contents($tmpZip));
        @unlink($tmpZip);

        return $relPath;
    }

    /**
     * Build one .sql file: header banner, parameter comments, then the SQL
     * with parameters substituted as quoted literals. We comment the original
     * `?`-placeholder form too for transparency.
     */
    private function buildSqlFile(DataDiscoveryScanPlan $plan, string $appName, array $q): string
    {
        $tableName = $q['table'] ?? 'unknown';
        $sqlTemplate = $q['sql'] ?? '';
        $params = $q['params'] ?? [];
        $confidence = $q['confidence'] ?? 'unknown';
        $matched = implode(', ', (array) ($q['matched_columns'] ?? []));

        $body = implode("\n", self::PRIVASIMU_HEADER_LINES)."\n";
        $body .= "-- Plan ID: {$plan->id}\n";
        $body .= "-- App: {$appName}\n";
        $body .= "-- Table: {$tableName}\n";
        $body .= "-- Match confidence: {$confidence}\n";
        $body .= "-- Matched columns: {$matched}\n";
        $body .= '-- Generated: '.now()->toIso8601String()."\n";
        $body .= "--\n";
        $body .= "-- ⚠️ EXECUTE ONLY ON A READ REPLICA. Privasimu has not run this query.\n";
        $body .= "-- The query is read-only (SELECT) but always validate before execution.\n";
        $body .= "--\n";
        $body .= "-- Original prepared form:\n";
        $body .= '--   '.trim(preg_replace('/\s+/', ' ', $sqlTemplate))."\n";
        foreach ($params as $i => $p) {
            $body .= sprintf("-- Param %d: %s\n", $i + 1, $this->commentEscape((string) $p));
        }
        $body .= '-- '.str_repeat('=', 65)."\n\n";

        $body .= $this->substituteParams($sqlTemplate, $params).";\n";

        return $body;
    }

    /**
     * Replace each positional `?` in the SQL string with a quoted SQL literal.
     * Uses naive `addslashes` + single-quote wrapping — admin DBA executes
     * manually, this is not a live DB driver. Numeric values still wrapped
     * in quotes; SQL implicit-cast handles them.
     */
    private function substituteParams(string $sql, array $params): string
    {
        $idx = 0;

        // Single-pass replacement so multiple ? in the same query each pull
        // the next param and we don't accidentally re-substitute a ? that was
        // part of a string literal we just inserted.
        return preg_replace_callback('/\?/', function () use ($params, &$idx) {
            if (! array_key_exists($idx, $params)) {
                return '?'; // leave unbound
            }
            $val = $params[$idx++];
            if ($val === null) {
                return 'NULL';
            }

            return "'".str_replace("'", "''", (string) $val)."'";
        }, $sql);
    }

    private function buildResultTemplate(DataDiscoveryScanPlan $plan): string
    {
        // Header CSV row — admin populates one row per hit. The frontend's
        // upload endpoint validates that masked_* columns actually carry
        // mask-shaped strings (DataDiscoveryMaskerService::validateMasked).
        $header = [
            'plan_system_id',
            'table',
            'confidence',
            'match_count',
            'row_pks_json',         // JSON array, e.g. [{"id":12842}]
            'matched_columns_json', // JSON array, e.g. ["email","name"]
            'masked_row_json',      // JSON object of masked column → value
        ];
        $sample = [
            '<plan_system_id from manifest.json>',
            'customers',
            'high',
            '1',
            '[{"id":12842}]',
            '["email","name"]',
            '{"email":"b***@e***.com","name":"Budi S***"}',
        ];

        return implode(',', $header)."\n".implode(',', array_map(fn ($v) => '"'.str_replace('"', '""', $v).'"', $sample))."\n";
    }

    private function buildReadme(DataDiscoveryScanPlan $plan, array $manifest): string
    {
        $base = rtrim(config('app.url') ?: url('/'), '/');
        $md = "# Person Scan Pack — {$plan->id}\n\n";
        $md .= 'Generated by '.(config('app.name') ?: 'Privasimu Nexus').' • '.now()->toIso8601String()."\n\n";

        $md .= "## What this pack is\n\n";
        $md .= "Privasimu generated a set of read-only `SELECT` queries that locate where this person's PII lives across your registered information systems. **Privasimu has not executed these queries** — you (the data administrator) run them on a read replica and upload the masked results back so the DPO can issue a DSR deletion / portability checklist.\n\n";

        $md .= "## ⚠️ Critical Safety Rules\n\n";
        $md .= "1. **Execute only on a READ REPLICA** — never on a primary write node.\n";
        $md .= "2. **Verify each query** is `SELECT ... LIMIT 100` and contains no destructive verbs.\n";
        $md .= "3. **Mask PII in the result** before uploading — see `result_template.csv` for the expected shape.\n";
        $md .= "4. **Do not edit `manifest.json`** — the upload validator uses it to map rows back to plan_system records.\n";
        $md .= '5. Pack expires on `'.($manifest['expires_at'] ?? 'N/A')."`.\n\n";

        $md .= "## Scope\n\n";
        $md .= "- Total systems: {$manifest['total_systems']}\n";
        $md .= "- Total tables: {$manifest['total_tables']}\n";
        $md .= '- Identifiers (masked): '.json_encode($manifest['identifiers_masked'], JSON_UNESCAPED_UNICODE)."\n\n";

        $md .= "## Files\n\n";
        $md .= "| # | File | App | Table | Confidence |\n";
        $md .= "|---|------|-----|-------|------------|\n";
        $i = 1;
        foreach ($manifest['scopes'] ?? [] as $s) {
            $md .= "| {$i} | `{$s['file']}` | {$s['app_name']} | `{$s['table']}` | {$s['confidence']} |\n";
            $i++;
        }
        $md .= "\n";

        $md .= "## Execution & Upload\n\n";
        $md .= "1. Run each `.sql` against your read replica.\n";
        $md .= "2. For each row returned, append a line to `result_template.csv` filled with:\n";
        $md .= "   - `plan_system_id` from `manifest.json` (matches the file's app+table).\n";
        $md .= "   - `row_pks_json` — JSON array of primary-key column → value pairs.\n";
        $md .= "   - `masked_row_json` — JSON object where every PII column is **masked** per Privasimu conventions (e.g. `b***@e***.com`).\n";
        $md .= "3. Upload the completed CSV at: `{$base}/data-discovery/scan-results/{$plan->id}` → **Upload Results**.\n";
        $md .= "4. The validator rejects rows whose masked columns still contain raw PII.\n\n";

        $md .= "## What Privasimu does NOT do\n\n";
        $md .= "- Does not execute SQL against your DB.\n";
        $md .= "- Does not store DB credentials.\n";
        $md .= "- Does not see the raw rows — only the masked values you upload.\n\n";

        return $md;
    }

    private function commentEscape(string $s): string
    {
        // Strip newlines so the param value can't break out of the comment line.
        return preg_replace('/\s+/', ' ', $s) ?? '';
    }

    private function slugify(string $s): string
    {
        $s = preg_replace('/[^A-Za-z0-9]+/', '_', $s) ?? '';
        $s = trim($s, '_');
        if ($s === '') {
            return 'X';
        }

        return mb_strtoupper(mb_substr($s, 0, 24));
    }
}
