<?php

namespace App\Services;

use App\Models\DsrExecution;
use App\Models\DsrRequest;
use App\Models\DsrRequestScope;
use App\Models\InformationSystem;
use App\Models\Organization;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

/**
 * DSR SQL Generator — produce SQL pack for DPO to hand-off ke admin klien.
 *
 * IMPORTANT INVARIANT:
 *   Privasimu TIDAK PERNAH execute SQL pada DB klien.
 *   Service ini hanya GENERATE SQL files + ZIP pack + safety README.
 *   Admin klien execute manually di sistem mereka, lalu upload evidence balik.
 *
 * Output structure (ZIP):
 *   dsr-DSR-2026-042.zip
 *   ├── README.md                                  ← instructions + safety warnings
 *   ├── manifest.json                              ← machine-readable scope summary
 *   ├── 01_CB_shard_01__deletion.sql               ← per IS per shard per type
 *   ├── 02_CB_shard_02__deletion.sql
 *   ├── 03_CRM__deletion.sql                       ← non-sharded systems no shard suffix
 *   └── 04_MARKETING__withdraw_consent.sql
 *
 * 7 generators: access, correction, deletion, portability, withdraw_consent,
 *               objection, restriction, info.
 */
class DsrSqlGeneratorService
{
    private const PRIVASIMU_HEADER_LINES = [
        '-- ╔══════════════════════════════════════════════════════════════════╗',
        '-- ║              GENERATED BY PRIVASIMU NEXUS                       ║',
        '-- ║         Subject Data Request (DSR) Fulfillment Pack              ║',
        '-- ╚══════════════════════════════════════════════════════════════════╝',
    ];

    /**
     * Generate full SQL pack untuk DSR. Creates DsrExecution placeholder rows
     * (status=pending) untuk setiap shard×type — admin klien fill in nanti.
     *
     * @return array{url: string, manifest: array, file_count: int, total_size: int}
     */
    public function generatePack(DsrRequest $dsr): array
    {
        $dsr->load(['scopes.informationSystem', 'app']);
        $scopes = $dsr->scopes;
        if ($scopes->isEmpty()) {
            throw new \RuntimeException('DSR belum di-assign scope. DPO harus pick Information Systems dulu.');
        }

        $files = [];
        $manifest = [
            'dsr_request_id' => $dsr->request_id,
            'dsr_uuid' => $dsr->id,
            'app_name' => $dsr->app?->name,
            'app_code' => $dsr->app?->app_code,
            'subject_email_hash' => substr(hash('sha256', $dsr->requester_email ?? ''), 0, 16),
            'request_type' => $dsr->request_type,
            'generated_at' => now()->toIso8601String(),
            'deadline_at' => $dsr->deadline_at?->toIso8601String(),
            'scopes' => [],
        ];

        $fileSeq = 1;
        foreach ($scopes as $scope) {
            $is = $scope->informationSystem;
            if (! $is) {
                continue;
            }
            $shards = $this->resolveShards($is, $scope);
            foreach ($shards as $shardName) {
                foreach ($scope->request_types ?? [] as $type) {
                    $sql = $this->generateForType($dsr, $is, $shardName, $type);
                    $code = $is->code ?: $this->slugify($is->name);
                    $shardSuffix = $shardName ? "_{$shardName}" : '';
                    $filename = sprintf('%02d_%s%s__%s.sql', $fileSeq, $code, $shardSuffix, $type);
                    $files[$filename] = $sql;
                    $manifest['scopes'][] = [
                        'file' => $filename,
                        'information_system' => $is->name,
                        'is_code' => $code,
                        'shard' => $shardName,
                        'request_type' => $type,
                        'is_sharded' => (bool) $is->is_sharded,
                    ];
                    $fileSeq++;

                    // Create or update DsrExecution placeholder (status=pending)
                    DsrExecution::firstOrCreate(
                        [
                            'dsr_request_id' => $dsr->id,
                            'information_system_id' => $is->id,
                            'shard_name' => $shardName,
                            'request_type' => $type,
                        ],
                        [
                            'sql_executed' => $sql,
                            'status' => 'pending',
                        ]
                    );
                }
            }
            $scope->update([
                'sql_pack_status' => 'generated',
                'sql_pack_generated_at' => now(),
            ]);
        }

        // Add README.md + manifest.json
        $files['README.md'] = $this->buildReadme($dsr, $manifest);
        $files['manifest.json'] = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);

        // Build ZIP
        $zipPath = $this->buildZip($dsr, $files);

        // Save signed URL pointer ke first scope (untuk download tracking)
        $firstScope = $scopes->first();
        if ($firstScope) {
            $firstScope->update(['sql_pack_url' => $zipPath]);
        }

        $totalSize = array_sum(array_map('strlen', $files));

        return [
            'storage_path' => $zipPath,
            'manifest' => $manifest,
            'file_count' => count($files),
            'total_size' => $totalSize,
        ];
    }

    /**
     * Resolve which shards untuk generate. Default: all shards from IS metadata.
     * Override via scope.shards_affected kalau DPO pilih subset.
     */
    private function resolveShards(InformationSystem $is, DsrRequestScope $scope): array
    {
        if (! $is->is_sharded) {
            return [null];
        }  // 1 file untuk non-sharded

        $picked = $scope->shards_affected ?? [];
        if (! empty($picked)) {
            return $picked;
        }

        // Fallback: all shards dari IS metadata
        $allShards = $is->shards ?? [];
        if (empty($allShards)) {
            return [null];
        }  // sharded but no shards listed → treat as 1

        return array_map(fn ($s) => is_array($s) ? ($s['name'] ?? $s) : $s, $allShards);
    }

    /**
     * Dispatch ke per-type generator.
     */
    private function generateForType(DsrRequest $dsr, InformationSystem $is, ?string $shard, string $type): string
    {
        return match ($type) {
            'access' => $this->buildAccessSql($dsr, $is, $shard),
            'correction', 'rectification' => $this->buildCorrectionSql($dsr, $is, $shard),
            'deletion', 'erasure' => $this->buildDeletionSql($dsr, $is, $shard),
            'portability' => $this->buildPortabilitySql($dsr, $is, $shard),
            'withdraw_consent' => $this->buildWithdrawSql($dsr, $is, $shard),
            'objection' => $this->buildObjectionSql($dsr, $is, $shard),
            'restriction' => $this->buildRestrictionSql($dsr, $is, $shard),
            'info' => $this->buildInfoSql($dsr, $is, $shard),
            default => $this->buildPlaceholderSql($dsr, $is, $shard, $type),
        };
    }

    // =========================================================================
    // Per-type generators
    // =========================================================================

    private function buildAccessSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'ACCESS REQUEST', 'Subject minta copy of personal data. SQL berisi SELECT only — TIDAK MODIFY data.');
        $w = $this->whereClauseTemplate($dsr);
        $tables = $this->guessPiiTables($is);
        $body = "BEGIN;\n\n";
        foreach ($tables as $t) {
            $body .= "-- Read PII rows from `{$t}`\n";
            $body .= "SELECT * FROM {$t}\n WHERE {$w};\n\n";
        }
        $body .= "COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildCorrectionSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'CORRECTION REQUEST', 'Subject minta data field di-update. ⚠️ TEMPLATE ONLY — DPO/admin EDIT field+value yang spesifik sebelum execute.');
        $w = $this->whereClauseTemplate($dsr);
        $body = "BEGIN;\n\n"
            ."-- TODO: replace `<table>`, `<column>`, `<new_value>` dengan input DPO\n"
            ."-- Contoh skenario: subject minta update alamat\n"
            ."UPDATE customers\n   SET address = '<new_value>',\n       updated_at = NOW()\n WHERE {$w};\n\n"
            ."-- Verify rows_affected sebelum commit\n"
            ."COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildDeletionSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'DELETION REQUEST', '⚠️ DESTRUCTIVE — irreversible. Subject minta data dihapus / di-anonymize. Verify legal block check (UU TPPU, UU 29/2004) sudah dilakukan DPO sebelum execute.');
        $w = $this->whereClauseTemplate($dsr);
        $tables = $this->guessPiiTables($is);
        $body = "BEGIN;\n\n";
        foreach ($tables as $t) {
            $body .= "-- Anonymize `{$t}`\n";
            $body .= "UPDATE {$t}\n   SET email = NULL,\n       phone = NULL,\n       name = '[DELETED]',\n       address = NULL,\n       nik = NULL,\n       updated_at = NOW()\n WHERE {$w};\n\n";
        }
        $body .= "-- Optional: hard delete activity log (kalau retention policy allow)\n";
        $body .= "-- DELETE FROM activity_log WHERE {$w};\n\n";
        $body .= "-- Verify rows_affected for each table sebelum commit\n";
        $body .= "COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildPortabilitySql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'PORTABILITY REQUEST', 'Subject minta data dalam format machine-readable untuk transfer ke service lain (Pasal 7 ayat 3 UU PDP). Output: SELECT yang admin export ke JSON/CSV/XML.');
        $w = $this->whereClauseTemplate($dsr);
        $tables = $this->guessPiiTables($is);
        $body = "BEGIN;\n\n"
            ."-- Export untuk subject — JSON aggregation pattern (PostgreSQL/MySQL 8+)\n"
            ."-- Untuk MySQL <8 atau MSSQL/Oracle, run separate SELECT per table dan merge di tool.\n\n";
        foreach ($tables as $t) {
            $body .= "SELECT * FROM {$t}\n WHERE {$w};\n\n";
        }
        $body .= "-- Format export: JSON (recommended), CSV, atau XML\n";
        $body .= "-- Manifest: include source_attestation signed by DPO untuk transfer ke service penerima\n";
        $body .= "COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildWithdrawSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'WITHDRAW CONSENT', 'Subject withdraw consent yang previously diberikan (Pasal 8 UU PDP). UPDATE flag/status. Cascade ke marketing list.');
        $w = $this->whereClauseTemplate($dsr);
        $body = "BEGIN;\n\n"
            ."-- Mark consent withdrawn\n"
            ."UPDATE consent_records\n   SET withdrawn_at = NOW(),\n       withdraw_reason = 'subject_request_dsr_{$dsr->request_id}'\n WHERE {$w}\n   AND withdrawn_at IS NULL;\n\n"
            ."-- Cascade: stop marketing\n"
            ."UPDATE marketing_subscribers\n   SET is_active = false,\n       unsubscribed_at = NOW()\n WHERE {$w};\n\n"
            ."COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildObjectionSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'OBJECTION REQUEST', 'Subject objection ke specific processing — biasanya profiling atau direct marketing (Pasal 9 UU PDP). DPO assess dulu apakah ada legitimate interest yang override.');
        $w = $this->whereClauseTemplate($dsr);
        $body = "BEGIN;\n\n"
            ."-- TODO DPO decision: ACCEPT (stop processing) atau REJECT (justify)\n"
            ."-- Kalau ACCEPT, jalankan UPDATE flag dibawah. Kalau REJECT, skip dan kasih decision letter.\n\n"
            ."UPDATE customer_preferences\n   SET allow_profiling = false,\n       allow_direct_marketing = false,\n       updated_at = NOW()\n WHERE {$w};\n\n"
            ."COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildRestrictionSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'RESTRICTION REQUEST', 'Subject minta processing di-pause sementara (selama dispute / verifikasi). Set status flag — JANGAN delete data, hanya block usage.');
        $w = $this->whereClauseTemplate($dsr);
        $body = "BEGIN;\n\n"
            ."-- Mark customer status restricted\n"
            ."UPDATE customers\n   SET status = 'processing_restricted',\n       restriction_reason = 'subject_request_dsr_{$dsr->request_id}',\n       restricted_at = NOW()\n WHERE {$w};\n\n"
            ."-- Optional: notify dependent services via app-level (di luar SQL)\n"
            ."COMMIT;\n";

        return $h.$body.$this->footer();
    }

    private function buildInfoSql(DsrRequest $dsr, InformationSystem $is, ?string $shard): string
    {
        $h = $this->header($dsr, $is, $shard, 'INFORMATION REQUEST', 'Subject tanya data apa, untuk apa, berapa lama. Tidak butuh SQL execution — render dari RoPA + Privacy Notice. File ini hanya placeholder.');

        return $h."-- INFO request tidak butuh SQL execution.\n"
            ."-- Generate Information Disclosure Letter via Privasimu UI (data dari RoPA).\n"
            ."-- File ini bisa di-skip (mark execution status='skipped').\n"
            .$this->footer();
    }

    private function buildPlaceholderSql(DsrRequest $dsr, InformationSystem $is, ?string $shard, string $type): string
    {
        $h = $this->header($dsr, $is, $shard, strtoupper($type).' REQUEST', 'Custom request type. SQL template manual — silakan modifikasi sesuai use case.');

        return $h."-- TODO: implement SQL untuk request type '{$type}'\n".$this->footer();
    }

    // =========================================================================
    // Header + Footer + Helpers
    // =========================================================================

    private function header(DsrRequest $dsr, InformationSystem $is, ?string $shard, string $title, string $note): string
    {
        $email = $dsr->requester_email ? $this->maskEmail($dsr->requester_email) : '<unknown>';
        $shardLabel = $shard ?: '(non-sharded)';
        $h = implode("\n", self::PRIVASIMU_HEADER_LINES)."\n";
        $h .= "-- {$title}\n";
        $h .= "-- DSR Reference: {$dsr->request_id}\n";
        $h .= "-- Information System: {$is->name} (code: {$is->code})\n";
        $h .= "-- Shard: {$shardLabel}\n";
        $h .= "-- Subject: {$email}\n";
        $h .= '-- Generated: '.now()->toIso8601String()."\n";
        $h .= '-- Deadline: '.($dsr->deadline_at?->toIso8601String() ?: 'N/A')."\n";
        $h .= "--\n";
        $h .= "-- ⚠️ NOTE\n";
        $h .= '-- '.wordwrap($note, 64, "\n-- ", true)."\n";
        $h .= "--\n";
        $h .= "-- BEFORE EXECUTING:\n";
        $h .= "-- 1. Verify subject identifiers di WHERE clause sesuai konvensi DB Anda\n";
        $h .= "-- 2. Run SELECT preview dulu untuk count expected rows\n";
        $h .= "-- 3. Backup table affected sebelum DESTRUCTIVE operation\n";
        $h .= "-- 4. Execute dalam transaction (BEGIN ... COMMIT)\n";
        $h .= "-- 5. Catat rows_affected, upload evidence ke Privasimu DSR page\n";
        $h .= '-- '.str_repeat('═', 65)."\n\n";

        return $h;
    }

    private function footer(): string
    {
        // Auto-detect base from APP_URL or current request host (white-label safe).
        $base = rtrim(config('app.url') ?: url('/'), '/');

        return "\n-- ".str_repeat('═', 65)."\n"
            ."-- After execution, upload evidence (rows_affected + screenshot) at:\n"
            ."-- {$base}/dsr — open this DSR detail → Executions tab\n";
    }

    /**
     * WHERE clause template based on subject_data identifiers + email.
     * Admin DPO/klien sesuaikan column name dengan konvensi DB mereka.
     */
    private function whereClauseTemplate(DsrRequest $dsr): string
    {
        $clauses = [];
        // email always
        $email = $dsr->requester_email ? str_replace("'", "''", $dsr->requester_email) : '<email>';
        $clauses[] = "email = '{$email}'";

        $sd = $dsr->subject_data ?? [];
        if (! empty($sd['nik'])) {
            $nik = preg_replace('/[^0-9]/', '', (string) $sd['nik']);
            $clauses[] = "OR nik = '{$nik}'";
        }
        if (! empty($sd['customer_id'])) {
            $cid = str_replace("'", "''", (string) $sd['customer_id']);
            $clauses[] = "OR customer_id = '{$cid}'";
        }
        if (! empty($sd['phone'])) {
            $phone = preg_replace('/[^0-9+]/', '', (string) $sd['phone']);
            $clauses[] = "OR phone = '{$phone}'";
        }

        return implode("\n   ", $clauses);
    }

    /**
     * Guess PII-bearing tables dari scan_results IS (kalau ada).
     * Fallback: generic table names umum.
     */
    private function guessPiiTables(InformationSystem $is): array
    {
        $scan = $is->scan_results ?? [];
        if (! empty($scan['pii_tables'])) {
            return is_array($scan['pii_tables']) ? array_slice($scan['pii_tables'], 0, 10) : [];
        }

        // Fallback: 3 common table names
        return ['customers', 'users', 'profiles'];
    }

    private function maskEmail(string $email): string
    {
        $parts = explode('@', $email);
        if (count($parts) !== 2) {
            return '***';
        }
        $local = $parts[0];
        $masked = mb_substr($local, 0, 2).str_repeat('*', max(1, mb_strlen($local) - 2));

        return $masked.'@'.$parts[1];
    }

    private function slugify(string $s): string
    {
        $s = preg_replace('/[^A-Za-z0-9]+/', '_', $s);

        return mb_strtoupper(mb_substr(trim($s, '_'), 0, 16));
    }

    // =========================================================================
    // README + ZIP Builder
    // =========================================================================

    private function buildReadme(DsrRequest $dsr, array $manifest): string
    {
        $deadline = $dsr->deadline_at?->format('Y-m-d H:i T') ?: 'N/A';
        $hoursLeft = $dsr->deadline_at ? max(0, now()->diffInHours($dsr->deadline_at, false)) : 'N/A';
        // Auto-detect base from APP_URL or current request host (white-label safe).
        $base = rtrim(config('app.url') ?: url('/'), '/');

        $md = "# DSR Fulfillment Pack — {$dsr->request_id}\n\n";
        $md .= '**Generated by '.(config('app.name') ?: 'Privasimu Nexus').'** • '.now()->toIso8601String()."\n\n";
        $md .= "## Request Info\n\n";
        $md .= "- **Reference**: `{$dsr->request_id}`\n";
        $md .= '- **App**: '.($dsr->app?->name ?: '(direct submission)')."\n";
        $md .= "- **Request Type**: `{$dsr->request_type}`\n";
        $md .= '- **Subject** (hashed): `'.substr(hash('sha256', $dsr->requester_email ?? ''), 0, 16)."`\n";
        $md .= "- **Deadline**: `{$deadline}` ({$hoursLeft} hours remaining)\n";
        $md .= "- **SLA**: 72 hours (UU PDP Pasal 32)\n\n";

        $md .= "## ⚠️ Critical Safety Rules\n\n";
        $md .= "1. **Privasimu TIDAK execute SQL** di DB Anda — Anda yang execute manual.\n";
        $md .= "2. **VERIFY WHERE clause** sesuai konvensi DB Anda (column name email/nik/customer_id mungkin beda).\n";
        $md .= "3. **Backup affected tables** sebelum execute DESTRUCTIVE operation (DELETE/UPDATE).\n";
        $md .= "4. **Run dalam transaction** (BEGIN ... COMMIT) — bisa ROLLBACK kalau ada error.\n";
        $md .= "5. **Upload evidence kembali** ke Privasimu page setelah execute (rows_affected + screenshot).\n\n";

        $md .= "## Files in This Pack\n\n";
        $md .= "| # | File | Information System | Shard | Type |\n";
        $md .= "|---|------|---------------------|-------|------|\n";
        $i = 1;
        foreach ($manifest['scopes'] ?? [] as $s) {
            $md .= "| {$i} | `{$s['file']}` | {$s['information_system']} | ".($s['shard'] ?: '-')." | `{$s['request_type']}` |\n";
            $i++;
        }
        $md .= "\n";

        $md .= "## Execution Steps\n\n";
        $md .= "1. **Open `manifest.json`** untuk machine-readable scope summary\n";
        $md .= "2. Untuk setiap `.sql` file:\n";
        $md .= "   a. Open in DB client (pgAdmin / MySQL Workbench / DBeaver)\n";
        $md .= "   b. Review SQL — terutama WHERE clause + table names\n";
        $md .= "   c. Run SELECT preview dulu untuk count expected rows\n";
        $md .= "   d. Execute dalam transaction\n";
        $md .= "   e. Note rows_affected\n";
        $md .= "3. **Upload evidence** per file di Privasimu DSR page:\n";
        $md .= "   - URL: `{$base}/dsr` → buka detail DSR `{$dsr->request_id}` → Executions tab\n";
        $md .= "   - Per file: input rows_affected + status (executed/failed/skipped) + upload screenshot\n";
        $md .= "4. Setelah semua execution evidence uploaded → DSR auto-completed → Subject Certificate generated\n\n";

        $md .= "## What Privasimu Does NOT Do\n\n";
        $md .= "- ❌ Execute SQL pada DB Anda\n";
        $md .= "- ❌ Store credential DB Anda\n";
        $md .= "- ❌ Modify data tanpa instruksi DPO Anda\n";
        $md .= "- ❌ Share data subject ke pihak ke-3\n\n";

        $md .= "## What Privasimu DOES Do\n\n";
        $md .= "- ✅ Generate SQL templates dari Schema Registry\n";
        $md .= "- ✅ Track 72-hour SLA + alert escalation\n";
        $md .= "- ✅ Audit trail end-to-end (who, what, when)\n";
        $md .= "- ✅ Generate Subject Certificate + Internal Certificate setelah completion\n";
        $md .= "- ✅ Send notification ke DPO + Subject\n\n";

        // Support contact: prefer org's own contact email if set, else generic
        $org = $dsr->organization ?? Organization::find($dsr->org_id);
        $supportContact = $org?->email
            ?: $org?->settings['support_email'] ?? null;
        $md .= "---\n";
        if ($supportContact) {
            $md .= "*Need help? Contact: {$supportContact}*\n";
        } else {
            $md .= "*Need help? Contact your organization's DPO team.*\n";
        }

        return $md;
    }

    /**
     * Build ZIP file dari files array, save ke storage, return path.
     */
    private function buildZip(DsrRequest $dsr, array $files): string
    {
        $tmpZip = tempnam(sys_get_temp_dir(), 'dsr-pack-');
        $zip = new ZipArchive;
        if ($zip->open($tmpZip, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Cannot create ZIP archive at '.$tmpZip);
        }
        foreach ($files as $name => $content) {
            $zip->addFromString($name, $content);
        }
        $zip->close();

        $relativePath = sprintf('dsr-packs/%s/%s.zip', $dsr->org_id, $dsr->request_id);
        $disk = Storage::disk('local');
        $disk->put($relativePath, file_get_contents($tmpZip));
        @unlink($tmpZip);

        return $relativePath;
    }
}
