<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

/**
 * Sprint G.10 — fix unique constraint di vendor_questionnaires.
 *
 * Bug ditemukan oleh ThirdPartyQuestionCustomizationTest:
 * test_edit_system_question_creates_fork + test_disable_system_question_creates_tombstone
 * gagal karena unique(category, version, question_code) TIDAK include org_id.
 * Saat tenant fork system row → INSERT dengan question_code sama → SQLSTATE 23000.
 *
 * Fix: drop unique key lama, replace dengan (category, version, question_code, org_id)
 * supaya tenant override boleh share question_code dengan system row (parent).
 */
return new class extends Migration {
    public function up(): void
    {
        // SQLite: drop + create. MySQL/PG: drop + add named.
        $driver = DB::connection()->getDriverName();

        Schema::table('vendor_questionnaires', function (Blueprint $table) use ($driver) {
            // Drop old unique. Index name auto-generated by Laravel:
            // vendor_questionnaires_category_version_question_code_unique
            try {
                $table->dropUnique(['category', 'version', 'question_code']);
            } catch (\Throwable $e) {
                // Index might not exist on fresh schema — fine.
            }
        });

        Schema::table('vendor_questionnaires', function (Blueprint $table) {
            // SQLite tidak support multi-column unique dengan NULL via index biasa —
            // untuk dev/test pakai composite unique. NULL di org_id di-treat sebagai
            // distinct value, jadi system row (org_id NULL) tidak collide dengan
            // tenant override (org_id UUID) pada question_code yang sama.
            $table->unique(['category', 'version', 'question_code', 'org_id'], 'vendor_q_unique_with_org');
        });
    }

    public function down(): void
    {
        Schema::table('vendor_questionnaires', function (Blueprint $table) {
            $table->dropUnique('vendor_q_unique_with_org');
            $table->unique(['category', 'version', 'question_code']);
        });
    }
};
