{{--
    Shared PDF layout for LIA / TIA / Maturity assessment exports.
    Honors tenant DocumentTemplate config (font, colors, header/footer).
--}}
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>@yield('title', $kindLabel)</title>
    @include('reports._doc_styles', ['config' => $config])
    <style>
        .doc-title { font-size: 18pt; font-weight: 800; color: {{ $config['primary_color'] ?? '#0f172a' }}; margin: 0 0 4px; letter-spacing: 0.5px; }
        .doc-sub { font-size: 10pt; color: #64748b; margin: 0 0 14px; }
        .doc-frame { border: 1px solid {{ $config['accent_color'] ?? '#0ea5e9' }}33; padding: 18px 22px; margin-top: 8px; }
        .meta-row { margin: 3px 0; font-size: 10pt; }
        .meta-row .lbl { display: inline-block; min-width: 170px; color: #475569; font-weight: 600; }
        .verdict-pill {
            display: inline-block; padding: 6px 14px; border-radius: 999px;
            font-size: 11pt; font-weight: 800; letter-spacing: 0.5px;
            text-transform: uppercase;
        }
        .v-pass { background: #dcfce7; color: #166534; }
        .v-fail { background: #fee2e2; color: #991b1b; }
        .v-cond { background: #fef3c7; color: #92400e; }
        .v-pending { background: #e2e8f0; color: #475569; }
        .score-card {
            display: inline-block; padding: 12px 18px; margin-right: 10px;
            border: 1px solid {{ $config['accent_color'] ?? '#0ea5e9' }}33;
            border-radius: 8px; vertical-align: top; min-width: 120px;
        }
        .score-card .num { font-size: 20pt; font-weight: 800; color: {{ $config['accent_color'] ?? '#0ea5e9' }}; }
        .score-card .lbl { font-size: 9pt; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
        .raci-grid { display: table; width: 100%; margin-top: 12px; }
        .raci-cell { display: table-cell; padding: 8px 12px; border-left: 3px solid {{ $config['accent_color'] ?? '#0ea5e9' }}; background: #f8fafc; vertical-align: top; }
        .raci-cell .role { font-size: 9pt; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
        .raci-cell .who { font-weight: 700; color: {{ $config['primary_color'] ?? '#0f172a' }}; font-size: 10pt; }
        .raci-cell .when { font-size: 8pt; color: #94a3b8; }
        .ruler-bar { height: 14px; background: #e2e8f0; border-radius: 4px; overflow: hidden; position: relative; margin: 4px 0; }
        .ruler-fill { height: 100%; }
        .stamp-id { font-family: monospace; font-size: 8pt; color: #94a3b8; margin-top: 6px; }
    </style>
</head>
<body>
    @if(($config['watermark_enabled'] ?? false) && !empty($config['watermark_text']))
        <div class="watermark">{{ $config['watermark_text'] }}</div>
    @endif

    @if(($config['header_enabled'] ?? true))
    <div class="header">
        <div class="header-left">
            @if(($config['header_show_logo'] ?? true) && ($orgLogoUrl ?? false))
                <img src="{{ $orgLogoUrl }}" alt="Logo">
            @else
                <span style="font-size: 13pt; font-weight: 800; color: {{ $config['primary_color'] }};">{{ $orgName }}</span>
            @endif
        </div>
        <div class="header-right">@yield('doc-id', $kindLabel)</div>
    </div>
    @endif

    @if(($config['footer_enabled'] ?? true))
    <div class="footer">
        <div class="footer-left">
            {{ $orgName }}
            @if(($config['footer_show_website'] ?? true) && ($orgWebsite ?? false)) · {{ $orgWebsite }} @endif
        </div>
        <div class="footer-right">
            Generated by Privasimu Nexus · {{ $generatedAt }} · oleh {{ $generatedBy }}
        </div>
    </div>
    @endif

    <div class="content-wrap">
        @yield('content')
    </div>
</body>
</html>
