<?php

namespace App\Jobs;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use App\Models\SystemLogAnalysis;
use App\Services\AiService;

class AnalyzeErrorLogJob implements ShouldQueue
{
    use Queueable;

    protected $errorSnippet;

    /**
     * Create a new job instance.
     */
    public function __construct(string $errorSnippet)
    {
        $this->errorSnippet = $errorSnippet;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        try {
            $prompt = "Tolong periksa exception log error backend Laravel di bawah ini. " .
                      "Buatkan analisa mendalam menggunakan bahasa Indonesia, formatlah balasan kamu murni dalam JSON (HANYA JSON OBJECT, tidak ada markdown codeblock). " .
                      "Penting: Return harus memiliki 4 field berikut: " .
                      "\n1. 'kesimpulan' (string - kesimpulan riwayat error)," .
                      "\n2. 'status' (string - 'sehat', 'peringatan', atau 'kritis')," .
                      "\n3. 'solusi_langkah_langkah' (array of strings - langkah penyelesaian masalah)," .
                      "\n4. 'file_yang_harus_diperiksa' (array of strings - path/nama file yang kemungkinan menyebabkan error jika ada)." .
                      "\n\nBerikut log errornya:\n" . $this->errorSnippet;

            $aiService = new AiService();
            $response = $aiService->ask($prompt, "", 2000);

            if (isset($response['raw'])) {
                $jsonStr = $response['raw'];
                if (preg_match('/\{.*\}/s', $response['raw'], $matches)) {
                    $jsonStr = $matches[0];
                }
                $analysisData = json_decode($jsonStr, true);
            } else {
                $analysisData = $response;
            }

            SystemLogAnalysis::create([
                'raw_log_snippet' => $this->errorSnippet,
                'ai_analysis' => is_array($analysisData) ? $analysisData : ['raw_response' => $response],
                'status' => is_array($analysisData) ? 'success' : 'failed',
                'error_message' => is_array($analysisData) ? null : 'Failed to parse AI response into JSON',
                'created_by' => null, // null means auto generated by system event
            ]);
        } catch (\Exception $e) {
            // Silently fail or log it internally (we don't want to infinite loop AI logging AI errors)
            \Illuminate\Support\Facades\Log::channel('single')->warning('AI Auto-analyzer failed: ' . $e->getMessage());
        }
    }
}
